export default {
    ANY: 'any',
    ARRAY: 'array',
    ARRAY_OF: 'arrayOf',
    BOOL: 'bool',
    ELEMENT: 'element',
    ELEMENT_TYPE: 'elementType',
    EXACT: 'exact',
    FUNC: 'func',
    INSTANCE_OF: 'instanceOf',
    NODE: 'node',
    NUMBER: 'number',
    OBJECT: 'object',
    OBJECT_OF: 'objectOf',
    ONE_OF: 'oneOf',
    ONE_OF_TYPE: 'oneOfType',
    SHAPE: 'shape',
    STRING: 'string',
    SYMBOL: 'symbol',
};
