import { CORE_SCALES_TOKEN_DEFAULTS } from './coreScalesConst';

const { CORE_SYSTEM_SCALE } = CORE_SCALES_TOKEN_DEFAULTS;

export const CORE_RADII_TOKEN_NAMES = {
    CORE_RADIUS_01_X: 'CORE_RADIUS_01_X',
    CORE_RADIUS_02_X: 'CORE_RADIUS_02_X',
    CORE_RADIUS_04_X: 'CORE_RADIUS_04_X',
    CORE_RADIUS_06_X: 'CORE_RADIUS_06_X',
    CORE_RADIUS_08_X: 'CORE_RADIUS_08_X',
    CORE_RADIUS_10_X: 'CORE_RADIUS_10_X',
    CORE_RADIUS_CIRCLE: 'CORE_RADIUS_CIRCLE',
    CORE_RADIUS_HALF_X: 'CORE_RADIUS_HALF_X',
    CORE_RADIUS_NONE_X: 'CORE_RADIUS_NONE_X',
};

export const CORE_RADII_TOKEN_DEFAULTS = {
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_01_X]: CORE_SYSTEM_SCALE,
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_02_X]: Math.round(
        CORE_SYSTEM_SCALE * 2,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_04_X]: Math.round(
        CORE_SYSTEM_SCALE * 4,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_06_X]: Math.round(
        CORE_SYSTEM_SCALE * 6,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_08_X]: Math.round(
        CORE_SYSTEM_SCALE * 8,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_10_X]: Math.round(
        CORE_SYSTEM_SCALE * 10,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_CIRCLE]: '100%',
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_HALF_X]: Math.round(
        CORE_SYSTEM_SCALE / 2,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_NONE_X]: 0,
};
