export const CORE_SCALES_TOKEN_NAMES = {
    CORE_SYSTEM_SCALE: 'CORE_SYSTEM_SCALE',
    CORE_TYPOGRAPHY_SCALE_AUGMENTED_FOURTH:
        'CORE_TYPOGRAPHY_SCALE_AUGMENTED_FOURTH',
    CORE_TYPOGRAPHY_SCALE_GOLDEN_RATIO: 'CORE_TYPOGRAPHY_SCALE_GOLDEN_RATIO',
    CORE_TYPOGRAPHY_SCALE_MAJOR_SECOND: 'CORE_TYPOGRAPHY_SCALE_MAJOR_SECOND',
    CORE_TYPOGRAPHY_SCALE_MAJOR_THIRD: 'CORE_TYPOGRAPHY_SCALE_MAJOR_THIRD',
    CORE_TYPOGRAPHY_SCALE_MINOR_SECOND: 'CORE_TYPOGRAPHY_SCALE_MINOR_SECOND',
    CORE_TYPOGRAPHY_SCALE_MINOR_THIRD: 'CORE_TYPOGRAPHY_SCALE_MINOR_THIRD',
    CORE_TYPOGRAPHY_SCALE_PERFECT_FIFTH: 'CORE_TYPOGRAPHY_SCALE_PERFECT_FIFTH',
    CORE_TYPOGRAPHY_SCALE_PERFECT_FOURTH:
        'CORE_TYPOGRAPHY_SCALE_PERFECT_FOURTH',
};

export const CORE_SCALES_TOKEN_DEFAULTS = {
    [CORE_SCALES_TOKEN_NAMES.CORE_SYSTEM_SCALE]: 4,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_AUGMENTED_FOURTH]: 1.414,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_GOLDEN_RATIO]: 1.618,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_MAJOR_SECOND]: 1.125,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_MAJOR_THIRD]: 1.25,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_MINOR_SECOND]: 1.067,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_MINOR_THIRD]: 1.2,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_PERFECT_FIFTH]: 1.5,
    [CORE_SCALES_TOKEN_NAMES.CORE_TYPOGRAPHY_SCALE_PERFECT_FOURTH]: 1.333,
};
