import { CORE_SCALES_TOKEN_DEFAULTS } from './coreScalesConst';

const { CORE_SYSTEM_SCALE } = CORE_SCALES_TOKEN_DEFAULTS;

export const CORE_SPACING_TOKEN_NAMES = {
    CORE_SPACING_01X: 'CORE_SPACING_01X',
    CORE_SPACING_02X: 'CORE_SPACING_02X',
    CORE_SPACING_03X: 'CORE_SPACING_03X',
    CORE_SPACING_04X: 'CORE_SPACING_04X',
    CORE_SPACING_05X: 'CORE_SPACING_05X',
    CORE_SPACING_06X: 'CORE_SPACING_06X',
    CORE_SPACING_07X: 'CORE_SPACING_07X',
    CORE_SPACING_08X: 'CORE_SPACING_08X',
    CORE_SPACING_09X: 'CORE_SPACING_09X',
    CORE_SPACING_10X: 'CORE_SPACING_10X',
    CORE_SPACING_11X: 'CORE_SPACING_11X',
    CORE_SPACING_HALFX: 'CORE_SPACING_HALFX',
    CORE_SPACING_NONE: 'CORE_SPACING_NONE',
    CORE_SPACING_QUARTERX: 'CORE_SPACING_QUARTERX',
};

export const CORE_SPACING_TOKEN_DEFAULTS = {
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_01X]: CORE_SYSTEM_SCALE,
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_02X]: Math.round(
        CORE_SYSTEM_SCALE * 2,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_03X]: Math.round(
        CORE_SYSTEM_SCALE * 3,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_04X]: Math.round(
        CORE_SYSTEM_SCALE * 4,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_05X]: Math.round(
        CORE_SYSTEM_SCALE * 5,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_06X]: Math.round(
        CORE_SYSTEM_SCALE * 6,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_07X]: Math.round(
        CORE_SYSTEM_SCALE * 7,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_08X]: Math.round(
        CORE_SYSTEM_SCALE * 8,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_09X]: Math.round(
        CORE_SYSTEM_SCALE * 9,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_10X]: Math.round(
        CORE_SYSTEM_SCALE * 10,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_11X]: Math.round(
        CORE_SYSTEM_SCALE * 11,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_HALFX]: Math.round(
        CORE_SYSTEM_SCALE / 2,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_NONE]: 0,
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_QUARTERX]: Math.round(
        CORE_SYSTEM_SCALE / 4,
    ),
};
