import { CORE_SCALES_TOKEN_DEFAULTS } from './coreScalesConst';

const { CORE_SYSTEM_SCALE } = CORE_SCALES_TOKEN_DEFAULTS;

export const CORE_SPACING_TOKEN_NAMES = {
    CORE_SPACING_01_X: 'CORE_SPACING_01_X',
    CORE_SPACING_02_X: 'CORE_SPACING_02_X',
    CORE_SPACING_03_X: 'CORE_SPACING_03_X',
    CORE_SPACING_04_X: 'CORE_SPACING_04_X',
    CORE_SPACING_05_X: 'CORE_SPACING_05_X',
    CORE_SPACING_06_X: 'CORE_SPACING_06_X',
    CORE_SPACING_07_X: 'CORE_SPACING_07_X',
    CORE_SPACING_08_X: 'CORE_SPACING_08_X',
    CORE_SPACING_09_X: 'CORE_SPACING_09_X',
    CORE_SPACING_10_X: 'CORE_SPACING_10_X',
    CORE_SPACING_11_X: 'CORE_SPACING_11_X',
    CORE_SPACING_HALF_X: 'CORE_SPACING_HALF_X',
    CORE_SPACING_NONE: 'CORE_SPACING_NONE',
    CORE_SPACING_QUARTER_X: 'CORE_SPACING_QUARTER_X',
};

export const CORE_SPACING_TOKEN_DEFAULTS = {
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_01_X]: CORE_SYSTEM_SCALE,
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_02_X]: Math.round(
        CORE_SYSTEM_SCALE * 2,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_03_X]: Math.round(
        CORE_SYSTEM_SCALE * 3,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_04_X]: Math.round(
        CORE_SYSTEM_SCALE * 4,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_05_X]: Math.round(
        CORE_SYSTEM_SCALE * 5,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_06_X]: Math.round(
        CORE_SYSTEM_SCALE * 6,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_07_X]: Math.round(
        CORE_SYSTEM_SCALE * 7,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_08_X]: Math.round(
        CORE_SYSTEM_SCALE * 8,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_09_X]: Math.round(
        CORE_SYSTEM_SCALE * 9,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_10_X]: Math.round(
        CORE_SYSTEM_SCALE * 10,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_11_X]: Math.round(
        CORE_SYSTEM_SCALE * 11,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_HALF_X]: Math.round(
        CORE_SYSTEM_SCALE / 2,
    ),
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_NONE]: 0,
    [CORE_SPACING_TOKEN_NAMES.CORE_SPACING_QUARTER_X]: Math.round(
        CORE_SYSTEM_SCALE / 4,
    ),
};
