import { CORE_SCALES_TOKEN_DEFAULTS } from './coreScalesConst';

const { CORE_SYSTEM_SCALE } = CORE_SCALES_TOKEN_DEFAULTS;

export const CORE_RADII_TOKEN_NAMES = {
    CORE_RADIUS_01X: 'CORE_RADIUS_01X',
    CORE_RADIUS_02X: 'CORE_RADIUS_02X',
    CORE_RADIUS_04X: 'CORE_RADIUS_04X',
    CORE_RADIUS_06X: 'CORE_RADIUS_06X',
    CORE_RADIUS_08X: 'CORE_RADIUS_08X',
    CORE_RADIUS_10X: 'CORE_RADIUS_10X',
    CORE_RADIUS_CIRCLE: 'CORE_RADIUS_CIRCLE',
    CORE_RADIUS_HALFX: 'CORE_RADIUS_HALFX',
    CORE_RADIUS_NONE: 'CORE_RADIUS_NONE',
};

export const CORE_RADII_TOKEN_DEFAULTS = {
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_01X]: CORE_SYSTEM_SCALE,
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_02X]: Math.round(CORE_SYSTEM_SCALE * 2),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_04X]: Math.round(CORE_SYSTEM_SCALE * 4),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_06X]: Math.round(CORE_SYSTEM_SCALE * 6),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_08X]: Math.round(CORE_SYSTEM_SCALE * 8),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_10X]: Math.round(
        CORE_SYSTEM_SCALE * 10,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_CIRCLE]: '100%',
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_HALFX]: Math.round(
        CORE_SYSTEM_SCALE / 2,
    ),
    [CORE_RADII_TOKEN_NAMES.CORE_RADIUS_NONE]: 0,
};
