export const CORE_STATES_TOKEN_NAMES = {
    CORE_STATE_DISABLED_OPACITY: 'CORE_STATE_DISABLED_OPACITY',
};

export const CORE_STATES_TOKEN_DEFAULTS = {
    [CORE_STATES_TOKEN_NAMES.CORE_STATE_DISABLED_OPACITY]: 0.3,
};
