import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const BADGE_VARIANTS = {
    AFFIRMATIVE: 'AFFIRMATIVE',
    CAUTIONARY: 'CAUTIONARY',
    DANGER: 'DANGER',
    INFO: 'INFO',
};

export const BADGE_TOKEN_NAMES = {
    BADGE_BG_COLOR: 'BADGE_BG_COLOR',
    BADGE_BORDER_RADIUS: 'BADGE_BORDER_RADIUS',
    BADGE_TEXT_COLOR: 'BADGE_TEXT_COLOR',
    BADGE_AFFIRMATIVE_BG_COLOR: 'BADGE_AFFIRMATIVE_BG_COLOR',
    BADGE_AFFIRMATIVE_TEXT_COLOR: 'BADGE_AFFIRMATIVE_TEXT_COLOR',
    BADGE_CAUTIONARY_BG_COLOR: 'BADGE_CAUTIONARY_BG_COLOR',
    BADGE_CAUTIONARY_TEXT_COLOR: 'BADGE_CAUTIONARY_TEXT_COLOR',
    BADGE_DANGER_BG_COLOR: 'BADGE_DANGER_BG_COLOR',
    BADGE_DANGER_TEXT_COLOR: 'BADGE_DANGER_TEXT_COLOR',
    BADGE_INFO_BG_COLOR: 'BADGE_INFO_BG_COLOR',
    BADGE_INFO_TEXT_COLOR: 'BADGE_INFO_TEXT_COLOR',
};

export const BADGE_TOKEN_DEFAULTS = {
    BADGE_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_04_X,
};
