import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const BUTTON_VARIANTS = {
    PRIMARY: 'PRIMARY',
    PRIMARY_DESTRUCTIVE: 'PRIMARY_DESTRUCTIVE',
    SECONDARY: 'SECONDARY',
    SECONDARY_DESTRUCTIVE: 'SECONDARY_DESTRUCTIVE',
};

const getBtnVariantTokenNames = (variant) => ({
    [`BUTTON_${variant}_ACTIVE_BG_COLOR`]: `BUTTON_${variant}_ACTIVE_BG_COLOR`,
    [`BUTTON_${variant}_ACTIVE_BORDER_COLOR`]: `BUTTON_${variant}_ACTIVE_BORDER_COLOR`,
    [`BUTTON_${variant}_ACTIVE_TEXT_COLOR`]: `BUTTON_${variant}_ACTIVE_TEXT_COLOR`,
    [`BUTTON_${variant}_BG_COLOR`]: `BUTTON_${variant}_BG_COLOR`,
    [`BUTTON_${variant}_BORDER_COLOR`]: `BUTTON_${variant}_BORDER_COLOR`,
    [`BUTTON_${variant}_FOCUS_INNER_COLOR`]: `BUTTON_${variant}_FOCUS_INNER_COLOR`,
    [`BUTTON_${variant}_FOCUS_OUTER_COLOR`]: `BUTTON_${variant}_FOCUS_OUTER_COLOR`,
    [`BUTTON_${variant}_TEXT_COLOR`]: `BUTTON_${variant}_TEXT_COLOR`,
    [`BUTTON_${variant}_HOVER_BG_COLOR`]: `BUTTON_${variant}_HOVER_BG_COLOR`,
    [`BUTTON_${variant}_HOVER_BORDER_COLOR`]: `BUTTON_${variant}_HOVER_BORDER_COLOR`,
    [`BUTTON_${variant}_HOVER_TEXT_COLOR`]: `BUTTON_${variant}_HOVER_TEXT_COLOR`,
    [`BUTTON_${variant}_FOCUS_HALO_INNER_COLOR`]: `BUTTON_${variant}_FOCUS_HALO_INNER_COLOR`,
    [`BUTTON_${variant}_FOCUS_HALO_OUTER_COLOR`]: `BUTTON_${variant}_FOCUS_HALO_OUTER_COLOR`,
    [`BUTTON_SPLIT_${variant}_BORDER_COLOR`]: `BUTTON_SPLIT_${variant}_HOVER_TEXT_COLOR`,
});

export const BUTTON_TOKEN_NAMES = {
    BUTTON_BORDER_RADIUS: 'BUTTON_BORDER_RADIUS',
    BUTTON_BORDER_WIDTH: 'BUTTON_BORDER_WIDTH',
    BUTTON_FONT_WEIGHT: 'BUTTON_FONT_WEIGHT',
};

export const BUTTON_TOKEN_DEFAULTS = {
    BUTTON_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_06_X,
    BUTTON_BORDER_WIDTH: 1,
    BUTTON_FONT_WEIGHT: 'normal',
};

export const BUTTON_PRIMARY_TOKEN_NAMES = getBtnVariantTokenNames(
    BUTTON_VARIANTS.PRIMARY,
);

export const BUTTON_SECONDARY_TOKEN_NAMES = getBtnVariantTokenNames(
    BUTTON_VARIANTS.SECONDARY,
);

export const BUTTON_PRIMARY_DESTRUCTIVE_TOKEN_NAMES = getBtnVariantTokenNames(
    BUTTON_VARIANTS.PRIMARY_DESTRUCTIVE,
);

export const BUTTON_SECONDARY_DESTRUCTIVE_TOKEN_NAMES = getBtnVariantTokenNames(
    BUTTON_VARIANTS.SECONDARY_DESTRUCTIVE,
);
