import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const DND_TOKEN_NAMES = {
    DND_DROPZONE_BORDER_RADIUS: 'DND_DROPZONE_BORDER_RADIUS',
    DND_DROPZONE_BG_COLOR: 'DND_DROPZONE_BG_COLOR',
    DND_DROPZONE_BORDER_COLOR: 'DND_DROPZONE_BORDER_COLOR',
    DND_DROPZONE_TEXT_COLOR: 'DND_DROPZONE_TEXT_COLOR',
    DND_DROPZONE_DENIED_BG_COLOR: 'DND_DROPZONE_DENIED_BG_COLOR',
    DND_DROPZONE_DENIED_BORDER_COLOR: 'DND_DROPZONE_DENIED_BORDER_COLOR',
    DND_DROPZONE_DENIED_TEXT_COLOR: 'DND_DROPZONE_DENIED_TEXT_COLOR',
};

export const DND_TOKEN_DEFAULTS = {
    DND_DROPZONE_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_04_X,
};
