import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const FORM_TOKEN_NAMES = {
    // Toggle Inputs
    FORM_CHECKED_ACCENT_COLOR: 'FORM_CHECKED_ACCENT_COLOR',
    FORM_CHECKED_ACCENT_COMPLIMENT_COLOR:
        'FORM_CHECKED_ACCENT_COMPLIMENT_COLOR',
    FORM_CHECKED_FOCUS_HALO_INNER_COLOR: 'FORM_CHECKED_FOCUS_HALO_INNER_COLOR',
    FORM_CHECKED_FOCUS_HALO_OUTER_COLOR: 'FORM_CHECKED_FOCUS_HALO_OUTER_COLOR',
    // Checkbox
    FORM_CHECKBOX_BORDER_RADIUS: 'FORM_CHECKBOX_BORDER_RADIUS',
    // Date Picker
    FORM_DATE_PICKER_OFF_RANGE_TEXT_COLOR:
        'FORM_DATE_PICKER_OFF_RANGE_TEXT_COLOR',
    // Inputs
    FORM_INPUT_BORDER_RADIUS: 'FORM_INPUT_BORDER_RADIUS',
    FORM_INPUT_BG_COLOR: 'FORM_INPUT_BG_COLOR',
    FORM_INPUT_DISABLED_BG_COLOR: 'FORM_INPUT_DISABLED_BG_COLOR',
    FORM_INPUT_DISABLED_PLACEHOLDER_TEXT_COLOR:
        'FORM_INPUT_DISABLED_PLACEHOLDER_TEXT_COLOR',
    FORM_INPUT_ERROR_BORDER_COLOR: 'FORM_INPUT_ERROR_BORDER_COLOR',
    FORM_INPUT_ERROR_BG_COLOR: 'FORM_INPUT_ERROR_BG_COLOR',
    FORM_INPUT_ERROR_FOCUS_HALO_INNER_COLOR:
        'FORM_INPUT_ERROR_FOCUS_HALO_INNER_COLOR',
    FORM_INPUT_ERROR_FOCUS_HALO_OUTER_COLOR:
        'FORM_INPUT_ERROR_FOCUS_HALO_OUTER_COLOR',
    FORM_INPUT_ERROR_PLACEHOLDER_TEXT_COLOR:
        'FORM_INPUT_ERROR_PLACEHOLDER_TEXT_COLOR',
    FORM_INPUT_FOCUS_HALO_INNER_COLOR: 'FORM_INPUT_FOCUS_HALO_INNER_COLOR',
    FORM_INPUT_FOCUS_HALO_OUTER_COLOR: 'FORM_INPUT_FOCUS_HALO_OUTER_COLOR',
    // FORM_INPUT_PLACEHOLDER_FONT_STYLE: 'FORM_INPUT_PLACEHOLDER_FONT_STYLE',
    FORM_INPUT_PLACEHOLDER_TEXT_COLOR: 'FORM_INPUT_PLACEHOLDER_TEXT_COLOR',
    FORM_INPUT_TEXT_COLOR: 'FORM_INPUT_TEXT_COLOR',
    // Menus
    FORM_MENU_BORDER_RADIUS: 'FORM_MENU_BORDER_RADIUS',
    FORM_MENU_SELECTED_BG_COLOR: 'FORM_MENU_SELECTED_BG_COLOR',
    FORM_MENU_SELECTED_FOCUS_BG_COLOR: 'FORM_MENU_SELECTED_FOCUS_BG_COLOR',
    FORM_MENU_SELECTED_FOCUS_TEXT_COLOR: 'FORM_MENU_SELECTED_FOCUS_TEXT_COLOR',
    FORM_MENU_SELECTED_TEXT_COLOR: 'FORM_MENU_SELECTED_TEXT_COLOR',
    // Pills
    FORM_PILL_BG_COLOR: 'FORM_PILL_BG_COLOR',
    FORM_PILL_TEXT_COLOR: 'FORM_PILL_TEXT_COLOR',
    // Toggle Switch
    // FORM_TOGGLE_SWITCH_KNOB_BOX_SHADOW: 'FORM_TOGGLE_SWITCH_KNOB_BOX_SHADOW',
    FORM_TOGGLE_SWITCH_KNOB_BORDER_COLOR:
        'FORM_TOGGLE_SWITCH_KNOB_BORDER_COLOR',
    FORM_TOGGLE_SWITCH_KNOB_COLOR: 'FORM_TOGGLE_SWITCH_KNOB_COLOR',
    FORM_TOGGLE_SWITCH_TRACK_COLOR: 'FORM_TOGGLE_SWITCH_TRACK_COLOR',
    FORM_TOGGLE_SWITCH_TRACK_HOVER_COLOR:
        'FORM_TOGGLE_SWITCH_TRACK_HOVER_COLOR',
    FORM_TOGGLE_SWITCH_ON_KNOB_COLOR: 'FORM_TOGGLE_SWITCH_ON_KNOB_COLOR',
    FORM_TOGGLE_SWITCH_ON_TRACK_COLOR: 'FORM_TOGGLE_SWITCH_ON_TRACK_COLOR',
    FORM_TOGGLE_SWITCH_ON_TRACK_HOVER_COLOR:
        'FORM_TOGGLE_SWITCH_ON_TRACK_HOVER_COLOR',
    FORM_TOGGLE_SWITCH_BUSY_ICON_COLOR: 'FORM_TOGGLE_SWITCH_BUSY_ICON_COLOR',
    FORM_TOGGLE_SWITCH_ON_BUSY_ICON_COLOR_COLOR:
        'FORM_TOGGLE_SWITCH_ON_BUSY_ICON_COLOR_COLOR',
    FORM_TOGGLE_SWITCH_ON_FOCUS_HALO_INNER_COLOR:
        'FORM_TOGGLE_SWITCH_ON_FOCUS_HALO_INNER_COLOR',
    FORM_TOGGLE_SWITCH_ON_FOCUS_HALO_OUTER_COLOR:
        'FORM_TOGGLE_SWITCH_ON_FOCUS_HALO_OUTER_COLOR',
};

export const FORM_TOKEN_DEFAULTS = {
    FORM_CHECKBOX_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_01_X,
    FORM_INPUT_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_02_X,
    FORM_MENU_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_02_X,
};
