import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const LINK_TOKEN_NAMES = {
    LINK_BORDER_RADIUS: 'LINK_BORDER_RADIUS',
    LINK_FOCUS_HALO_INNER_COLOR: 'LINK_FOCUS_HALO_INNER_COLOR',
    LINK_FOCUS_HALO_OUTER_COLOR: 'LINK_FOCUS_HALO_OUTER_COLOR',
    LINK_TEXT_COLOR: 'LINK_TEXT_COLOR',
    LINK_TEXT_DECORATION: 'LINK_TEXT_DECORATION',
};

export const LINK_TOKEN_DEFAULTS = {
    LINK_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_02_X,
};
