import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const MODAL_TOKEN_NAMES = {
    MODAL_DIALOG_BORDER_RADIUS: 'MODAL_DIALOG_BORDER_RADIUS',
    MODAL_OVERLAY_BG_COLOR: 'MODAL_OVERLAY_BG_COLOR',
};

export const MODAL_TOKEN_DEFAULTS = {
    MODAL_DIALOG_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_04_X,
};
