/* eslint-disable import/prefer-default-export */
export const TABS_TOKEN_NAMES = {
    TABS_ACTIVE_ACCENT_COLOR: 'TABS_ACTIVE_ACCENT_COLOR',
    TABS_ACTIVE_BG_COLOR: 'TABS_ACTIVE_BG_COLOR',
    TABS_ACTIVE_FOCUS_HALO_INNER_COLOR: 'TABS_ACTIVE_FOCUS_HALO_INNER_COLOR',
    TABS_ACTIVE_FOCUS_HALO_OUTER_COLOR: 'TABS_ACTIVE_FOCUS_HALO_OUTER_COLOR',
    TABS_ACTIVE_TEXT_COLOR: 'TABS_ACTIVE_TEXT_COLOR',
    TABS_BORDER_COLOR: 'TABS_BORDER_COLOR',
    TABS_INACTIVE_BG_COLOR: 'TABS_INACTIVE_BG_COLOR',
    TABS_INACTIVE_TEXT_COLOR: 'TABS_INACTIVE_TEXT_COLOR',
    TABS_INACTIVE_HOVER_BG_COLOR: 'TABS_INACTIVE_HOVER_BG_COLOR',
    TABS_INACTIVE_HOVER_TEXT_COLOR: 'TABS_INACTIVE_HOVER_TEXT_COLOR',
    TABS_PANEL_BG_COLOR: 'TABS_PANEL_BG_COLOR',
};
