import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const TILE_TOKEN_NAMES = {
    TILE_BORDER_RADIUS: 'TILE_BORDER_RADIUS',
    TILE_HEADING_FONT_WEIGHT: 'TILE_HEADING_FONT_WEIGHT',
    TILE_HEADING_FONT_STYLE: 'TILE_HEADING_FONT_STYLE',
};

export const TILE_TOKEN_DEFAULTS = {
    TILE_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_04_X,
    TILE_HEADING_FONT_WEIGHT: 'normal',
    TILE_HEADING_FONT_STYLE: 'normal',
};
