import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const TOASTER_TOKEN_NAMES = {
    TOASTER_BORDER_RADIUS: 'TOASTER_BORDER_RADIUS',
    TOASTER_AFFIRMATIVE_BG_COLOR: 'TOASTER_AFFIRMATIVE_BG_COLOR',
    TOASTER_AFFIRMATIVE_TEXT_COLOR: 'TOASTER_AFFIRMATIVE_TEXT_COLOR',
    TOASTER_AFFIRMATIVE_PROGRESS_BAR_COLOR:
        'TOASTER_AFFIRMATIVE_PROGRESS_BAR_COLOR',
    TOASTER_BG_COLOR: 'TOASTER_BG_COLOR',
    TOASTER_CAUTIONARY_BG_COLOR: 'TOASTER_CAUTIONARY_BG_COLOR',
    TOASTER_CAUTIONARY_TEXT_COLOR: 'TOASTER_CAUTIONARY_TEXT_COLOR',
    TOASTER_CAUTIONARY_PROGRESS_BAR_COLOR:
        'TOASTER_CAUTIONARY_PROGRESS_BAR_COLOR',
    TOASTER_ERROR_BG_COLOR: 'TOASTER_ERROR_BG_COLOR',
    TOASTER_ERROR_TEXT_COLOR: 'TOASTER_ERROR_TEXT_COLOR',
    TOASTER_ERROR_PROGRESS_BAR_COLOR: 'TOASTER_ERROR_PROGRESS_BAR_COLOR',
    TOASTER_INFO_BG_COLOR: 'TOASTER_INFO_BG_COLOR',
    TOASTER_INFO_TEXT_COLOR: 'TOASTER_INFO_TEXT_COLOR',
    TOASTER_INFO_PROGRESS_BAR_COLOR: 'TOASTER_INFO_PROGRESS_BAR_COLOR',
    TOASTER_PROGRESS_BAR_COLOR: 'TOASTER_PROGRESS_BAR_COLOR',
    TOASTER_TEXT_COLOR: 'TOASTER_TEXT_COLOR',
};

export const TOASTER_TOKEN_DEFAULTS = {
    TOASTER_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_02_X,
};
