import { CORE_RADII_TOKEN_DEFAULTS } from '../core/coreRadiiConst';

export const TOOLTIP_TOKEN_NAMES = {
    TOOLTIP_BORDER_RADIUS: 'TOOLTIP_BORDER_RADIUS',
    TOOLTIP_ICON_COLOR: 'TOOLTIP_ICON_COLOR',
};

export const TOOLTIP_TOKEN_DEFAULTS = {
    TOOLTIP_BORDER_RADIUS: CORE_RADII_TOKEN_DEFAULTS.CORE_RADIUS_02_X,
};
