/* eslint-disable import/prefer-default-export */
import { getNewColorByChangingLightness } from '@epr0t0type/bankai-lib-color-utils';
import { COLOR_TOKEN_NAMES } from './colorTokensConst';
import { SPEC_TOKEN_DEFAULTS } from './specTokensConst';
import {
    COLOR_NEUTRAL_DEFAULTS,
    COLOR_WHITE,
} from './colorNeutralTokenDefaultsConst';

const COLOR_DT_BRAND = '#00aeff';
const COLOR_DT_PRIMARY = COLOR_DT_BRAND;
const COLOR_DT_SECONDARY = '#4798b8';
const COLOR_DT_CANVAS = COLOR_NEUTRAL_DEFAULTS.COLOR_NEUTRAL_10;
const COLOR_DT_CANVAS_ALT = getNewColorByChangingLightness(
    COLOR_NEUTRAL_DEFAULTS.COLOR_NEUTRAL_20,
    15,
);
const COLOR_DT_UNIVERSAL_HOVER_BG = COLOR_NEUTRAL_DEFAULTS.COLOR_NEUTRAL_20;
const COLOR_DT_UNIVERSAL_BORDER = COLOR_NEUTRAL_DEFAULTS.COLOR_NEUTRAL_30;
const COLOR_DT_ACCENT = '#876996';
const COLOR_DT_AFFIRMATIVE = '#54ab58';
const COLOR_DT_CAUTIONARY = '#fccf03';
const COLOR_DT_ERROR = '#cc3333';
const COLOR_DT_DESTRUCTIVE = COLOR_DT_ERROR;
const COLOR_DT_INFO = '#1979e6';
const COLOR_DT_LINK = '#4794eb';
const COLOR_DT_TEXT = COLOR_WHITE;
const COLOR_DT_TEXT_ALT = COLOR_NEUTRAL_DEFAULTS.COLOR_NEUTRAL_60;

export const DARK_THEME_TOKEN_DEFAULTS = {
    ...SPEC_TOKEN_DEFAULTS,
    ...COLOR_NEUTRAL_DEFAULTS,
    [COLOR_TOKEN_NAMES.COLOR_BRAND]: COLOR_DT_BRAND,
    [COLOR_TOKEN_NAMES.COLOR_PRIMARY]: COLOR_DT_PRIMARY,
    [COLOR_TOKEN_NAMES.COLOR_SECONDARY]: COLOR_DT_SECONDARY,
    [COLOR_TOKEN_NAMES.COLOR_ACCENT]: COLOR_DT_ACCENT,
    [COLOR_TOKEN_NAMES.COLOR_UNIVERSAL_BORDER]: COLOR_DT_UNIVERSAL_BORDER,
    [COLOR_TOKEN_NAMES.COLOR_UNIVERSAL_HOVER_BG]: COLOR_DT_UNIVERSAL_HOVER_BG,
    [COLOR_TOKEN_NAMES.COLOR_CANVAS]: COLOR_DT_CANVAS,
    [COLOR_TOKEN_NAMES.COLOR_CANVAS_ALT]: COLOR_DT_CANVAS_ALT,
    [COLOR_TOKEN_NAMES.COLOR_AFFIRMATIVE]: COLOR_DT_AFFIRMATIVE,
    [COLOR_TOKEN_NAMES.COLOR_CAUTIONARY]: COLOR_DT_CAUTIONARY,
    [COLOR_TOKEN_NAMES.COLOR_ERROR]: COLOR_DT_ERROR,
    [COLOR_TOKEN_NAMES.COLOR_DESTRUCTIVE]: COLOR_DT_DESTRUCTIVE,
    [COLOR_TOKEN_NAMES.COLOR_INFO]: COLOR_DT_INFO,
    [COLOR_TOKEN_NAMES.COLOR_LINK]: COLOR_DT_LINK,
    [COLOR_TOKEN_NAMES.COLOR_TEXT]: COLOR_DT_TEXT,
    [COLOR_TOKEN_NAMES.COLOR_TEXT_ALT]: COLOR_DT_TEXT_ALT,
};
