import { getNewColorByChangingLightness } from '@driponfleek/bankai-lib-color-utils';
import { CORE_NEUTRAL_COLOR_TOKEN_DEFAULTS } from '../core/coreColorsConst';

const ACCENT_COLOR = '#362a3c';
const ERROR_COLOR = '#cc3333';
const PRIMARY_COLOR = '#006fa3';
// const PRIMARY_COLOR = '#68768d';
const {
    CORE_COLOR_NEUTRAL_0,
    CORE_COLOR_NEUTRAL_30,
    CORE_COLOR_NEUTRAL_50,
    CORE_COLOR_NEUTRAL_80,
    CORE_COLOR_NEUTRAL_90,
    CORE_COLOR_NEUTRAL_100,
} = CORE_NEUTRAL_COLOR_TOKEN_DEFAULTS;

export const SEMANTIC_COLOR_TOKEN_NAMES = {
    SEMANTIC_COLOR_ACCENT: 'SEMANTIC_COLOR_ACCENT',
    SEMANTIC_COLOR_AFFIRMATIVE: 'SEMANTIC_COLOR_AFFIRMATIVE',
    SEMANTIC_COLOR_BRAND: 'SEMANTIC_COLOR_BRAND',
    SEMANTIC_COLOR_CANVAS: 'SEMANTIC_COLOR_CANVAS',
    SEMANTIC_COLOR_CANVAS_ALT: 'SEMANTIC_COLOR_CANVAS_ALT',
    SEMANTIC_COLOR_CANVAS_BRAND: 'SEMANTIC_COLOR_CANVAS_BRAND',
    SEMANTIC_COLOR_CANVAS_BRAND_TEXT: 'SEMANTIC_COLOR_CANVAS_BRAND_TEXT',
    SEMANTIC_COLOR_CAUTIONARY: 'SEMANTIC_COLOR_CAUTIONARY',
    SEMANTIC_COLOR_DESTRUCTIVE: 'SEMANTIC_COLOR_DESTRUCTIVE',
    SEMANTIC_COLOR_ERROR: 'SEMANTIC_COLOR_ERROR',
    SEMANTIC_COLOR_HEADINGS_TEXT: 'SEMANTIC_COLOR_HEADINGS_TEXT',
    SEMANTIC_COLOR_INFO: 'SEMANTIC_COLOR_INFO',
    SEMANTIC_COLOR_PRIMARY: 'SEMANTIC_COLOR_PRIMARY',
    SEMANTIC_COLOR_SECONDARY: 'SEMANTIC_COLOR_SECONDARY',
    SEMANTIC_COLOR_TEXT: 'SEMANTIC_COLOR_TEXT',
    SEMANTIC_COLOR_TEXT_ALT: 'SEMANTIC_COLOR_TEXT_ALT',
    SEMANTIC_COLOR_TEXT_ERROR: 'SEMANTIC_COLOR_TEXT_ERROR',
    SEMANTIC_COLOR_UNIVERSAL_ACCESSIBLE_BORDER:
        'SEMANTIC_COLOR_UNIVERSAL_ACCESSIBLE_BORDER',
    SEMANTIC_COLOR_UNIVERSAL_DECORATIVE_BORDER:
        'SEMANTIC_COLOR_UNIVERSAL_DECORATIVE_BORDER',
    SEMANTIC_COLOR_UNIVERSAL_FOCUS_HALO_INNER:
        'SEMANTIC_COLOR_UNIVERSAL_FOCUS_HALO_INNER',
    SEMANTIC_COLOR_UNIVERSAL_FOCUS_HALO_OUTER:
        'SEMANTIC_COLOR_UNIVERSAL_FOCUS_HALO_OUTER',
    SEMANTIC_COLOR_UNIVERSAL_HOVER_BG: 'SEMANTIC_COLOR_UNIVERSAL_HOVER_BG',
};

export const SEMANTIC_COLOR_TOKEN_DEFAULTS = {
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ACCENT]: ACCENT_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_AFFIRMATIVE]: '#3c7b3f',
    // [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_AFFIRMATIVE]: '#438946',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_BRAND]: PRIMARY_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS]: CORE_COLOR_NEUTRAL_100,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS_ALT]:
        getNewColorByChangingLightness(CORE_COLOR_NEUTRAL_90, 95),
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS_BRAND]: ACCENT_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS_BRAND_TEXT]:
        CORE_COLOR_NEUTRAL_100,
    // [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CAUTIONARY]: '#c5e50b',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CAUTIONARY]: '#b58102',
    // [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CAUTIONARY]: '#a28502',
    // [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CAUTIONARY]: '#fccf03',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_DESTRUCTIVE]: ERROR_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ERROR]: ERROR_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_HEADINGS_TEXT]:
        CORE_COLOR_NEUTRAL_0,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_INFO]: '#1979e6',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_PRIMARY]: PRIMARY_COLOR,
    // [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_SECONDARY]: PRIMARY_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_SECONDARY]: '#397a93',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT]: CORE_COLOR_NEUTRAL_0,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT_ALT]: CORE_COLOR_NEUTRAL_30,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT_ERROR]: ERROR_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_UNIVERSAL_DECORATIVE_BORDER]:
        CORE_COLOR_NEUTRAL_80,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_UNIVERSAL_ACCESSIBLE_BORDER]:
        CORE_COLOR_NEUTRAL_50,
};
