import { getNewColorByLightnessAdjustment } from '@driponfleek/bankai-lib-color-utils';
import {
    CORE_NEUTRAL_COLOR_TOKEN_DEFAULTS,
    CORE_COLOR_NEUTRAL_SEED_DEFAULT,
} from '../core/coreColorsConst';

const {
    CORE_COLOR_NEUTRAL_0,
    CORE_COLOR_NEUTRAL_30,
    CORE_COLOR_NEUTRAL_50,
    CORE_COLOR_NEUTRAL_80,
    CORE_COLOR_NEUTRAL_90,
    CORE_COLOR_NEUTRAL_100,
} = CORE_NEUTRAL_COLOR_TOKEN_DEFAULTS;

export const SEMANTIC_COLOR_TOKEN_NAMES = {
    // ACCENT PRIMARY
    SEMANTIC_COLOR_ACCENT_PRIMARY: 'SEMANTIC_COLOR_ACCENT_PRIMARY',
    SEMANTIC_COLOR_ACCENT_PRIMARY_TEXT: 'SEMANTIC_COLOR_ACCENT_PRIMARY_TEXT',
    SEMANTIC_COLOR_ACCENT_PRIMARY_DECORATIVE:
        'SEMANTIC_COLOR_ACCENT_PRIMARY_DECORATIVE',
    SEMANTIC_COLOR_ACCENT_PRIMARY_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_ACCENT_PRIMARY_TEXT_DECORATIVE',
    SEMANTIC_COLOR_ACCENT_PRIMARY_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_ACCENT_PRIMARY_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_ACCENT_PRIMARY_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_ACCENT_PRIMARY_TEXT_DECORATIVE_ACCENT',
    // ACCENT SECONDARY
    SEMANTIC_COLOR_ACCENT_SECONDARY: 'SEMANTIC_COLOR_ACCENT_SECONDARY',
    SEMANTIC_COLOR_ACCENT_SECONDARY_TEXT:
        'SEMANTIC_COLOR_ACCENT_SECONDARY_TEXT',
    SEMANTIC_COLOR_ACCENT_SECONDARY_DECORATIVE:
        'SEMANTIC_COLOR_ACCENT_SECONDARY_DECORATIVE',
    SEMANTIC_COLOR_ACCENT_SECONDARY_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_ACCENT_SECONDARY_TEXT_DECORATIVE',
    SEMANTIC_COLOR_ACCENT_SECONDARY_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_ACCENT_SECONDARY_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_ACCENT_SECONDARY_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_ACCENT_SECONDARY_TEXT_DECORATIVE_ACCENT',
    // ACCENT TERTIARY
    SEMANTIC_COLOR_ACCENT_TERTIARY: 'SEMANTIC_COLOR_ACCENT_TERTIARY',
    SEMANTIC_COLOR_ACCENT_TERTIARY_TEXT: 'SEMANTIC_COLOR_ACCENT_TERTIARY_TEXT',
    SEMANTIC_COLOR_ACCENT_TERTIARY_DECORATIVE:
        'SEMANTIC_COLOR_ACCENT_TERTIARY_DECORATIVE',
    SEMANTIC_COLOR_ACCENT_TERTIARY_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_ACCENT_TERTIARY_TEXT_DECORATIVE',
    SEMANTIC_COLOR_ACCENT_TERTIARY_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_ACCENT_TERTIARY_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_ACCENT_TERTIARY_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_ACCENT_TERTIARY_TEXT_DECORATIVE_ACCENT',
    // AFFIRMATIVE
    SEMANTIC_COLOR_AFFIRMATIVE: 'SEMANTIC_COLOR_AFFIRMATIVE',
    SEMANTIC_COLOR_AFFIRMATIVE_TEXT: 'SEMANTIC_COLOR_AFFIRMATIVE_TEXT',
    SEMANTIC_COLOR_AFFIRMATIVE_DECORATIVE:
        'SEMANTIC_COLOR_AFFIRMATIVE_DECORATIVE',
    SEMANTIC_COLOR_AFFIRMATIVE_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_AFFIRMATIVE_TEXT_DECORATIVE',
    SEMANTIC_COLOR_AFFIRMATIVE_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_AFFIRMATIVE_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_AFFIRMATIVE_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_AFFIRMATIVE_TEXT_DECORATIVE_ACCENT',
    // BRAND
    SEMANTIC_COLOR_BRAND: 'SEMANTIC_COLOR_BRAND',
    SEMANTIC_COLOR_BRAND_TEXT: 'SEMANTIC_COLOR_BRAND_TEXT',
    SEMANTIC_COLOR_BRAND_DECORATIVE: 'SEMANTIC_COLOR_BRAND_DECORATIVE',
    SEMANTIC_COLOR_BRAND_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_BRAND_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_BRAND_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_BRAND_DECORATIVE_ACCENT_TEXT',
    SEMANTIC_COLOR_BRAND_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_BRAND_DECORATIVE_TEXT',
    // CANVAS and CANVAS ALT
    SEMANTIC_COLOR_CANVAS: 'SEMANTIC_COLOR_CANVAS',
    SEMANTIC_COLOR_CANVAS_ALT: 'SEMANTIC_COLOR_CANVAS_ALT',
    // CANVAS BRAND
    SEMANTIC_COLOR_CANVAS_BRAND: 'SEMANTIC_COLOR_CANVAS_BRAND',
    SEMANTIC_COLOR_CANVAS_BRAND_TEXT: 'SEMANTIC_COLOR_CANVAS_BRAND_TEXT',
    SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE:
        'SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE',
    SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE_ACCENT_TEXT',
    SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_CANVAS_BRAND_DECORATIVE_TEXT',
    // CAUTIONARY
    SEMANTIC_COLOR_CAUTIONARY: 'SEMANTIC_COLOR_CAUTIONARY',
    SEMANTIC_COLOR_CAUTIONARY_TEXT: 'SEMANTIC_COLOR_CAUTIONARY_TEXT',
    SEMANTIC_COLOR_CAUTIONARY_DECORATIVE:
        'SEMANTIC_COLOR_CAUTIONARY_DECORATIVE',
    SEMANTIC_COLOR_CAUTIONARY_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_CAUTIONARY_TEXT_DECORATIVE',
    SEMANTIC_COLOR_CAUTIONARY_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_CAUTIONARY_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_CAUTIONARY_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_CAUTIONARY_TEXT_DECORATIVE_ACCENT',
    // DESTRUCTIVE
    SEMANTIC_COLOR_DESTRUCTIVE: 'SEMANTIC_COLOR_DESTRUCTIVE',
    SEMANTIC_COLOR_DESTRUCTIVE_TEXT: 'SEMANTIC_COLOR_DESTRUCTIVE_TEXT',
    SEMANTIC_COLOR_DESTRUCTIVE_DECORATIVE:
        'SEMANTIC_COLOR_DESTRUCTIVE_DECORATIVE',
    SEMANTIC_COLOR_DESTRUCTIVE_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_DESTRUCTIVE_TEXT_DECORATIVE',
    SEMANTIC_COLOR_DESTRUCTIVE_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_DESTRUCTIVE_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_DESTRUCTIVE_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_DESTRUCTIVE_TEXT_DECORATIVE_ACCENT',
    // ERROR
    SEMANTIC_COLOR_ERROR: 'SEMANTIC_COLOR_ERROR',
    SEMANTIC_COLOR_ERROR_TEXT: 'SEMANTIC_COLOR_ERROR_TEXT',
    SEMANTIC_COLOR_ERROR_DECORATIVE: 'SEMANTIC_COLOR_ERROR_DECORATIVE',
    SEMANTIC_COLOR_ERROR_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_ERROR_TEXT_DECORATIVE',
    SEMANTIC_COLOR_ERROR_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_ERROR_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_ERROR_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_ERROR_TEXT_DECORATIVE_ACCENT',
    // INFO
    SEMANTIC_COLOR_INFO: 'SEMANTIC_COLOR_INFO',
    SEMANTIC_COLOR_INFO_TEXT: 'SEMANTIC_COLOR_INFO_TEXT',
    SEMANTIC_COLOR_INFO_DECORATIVE: 'SEMANTIC_COLOR_INFO_DECORATIVE',
    SEMANTIC_COLOR_INFO_DECORATIVE_TEXT: 'SEMANTIC_COLOR_INFO_TEXT_DECORATIVE',
    SEMANTIC_COLOR_INFO_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_INFO_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_INFO_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_INFO_TEXT_DECORATIVE_ACCENT',
    // PRIMARY
    SEMANTIC_COLOR_PRIMARY: 'SEMANTIC_COLOR_PRIMARY',
    SEMANTIC_COLOR_PRIMARY_TEXT: 'SEMANTIC_COLOR_PRIMARY_TEXT',
    SEMANTIC_COLOR_PRIMARY_DECORATIVE: 'SEMANTIC_COLOR_PRIMARY_DECORATIVE',
    SEMANTIC_COLOR_PRIMARY_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_PRIMARY_TEXT_DECORATIVE',
    SEMANTIC_COLOR_PRIMARY_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_PRIMARY_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_PRIMARY_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_PRIMARY_TEXT_DECORATIVE_ACCENT',
    // SECONDARY
    SEMANTIC_COLOR_SECONDARY: 'SEMANTIC_COLOR_SECONDARY',
    SEMANTIC_COLOR_SECONDARY_TEXT: 'SEMANTIC_COLOR_SECONDARY_TEXT',
    SEMANTIC_COLOR_SECONDARY_DECORATIVE: 'SEMANTIC_COLOR_SECONDARY_DECORATIVE',
    SEMANTIC_COLOR_SECONDARY_DECORATIVE_TEXT:
        'SEMANTIC_COLOR_SECONDARY_TEXT_DECORATIVE',
    SEMANTIC_COLOR_SECONDARY_DECORATIVE_ACCENT:
        'SEMANTIC_COLOR_SECONDARY_DECORATIVE_ACCENT',
    SEMANTIC_COLOR_SECONDARY_DECORATIVE_ACCENT_TEXT:
        'SEMANTIC_COLOR_SECONDARY_TEXT_DECORATIVE_ACCENT',
    // TEXT COLORS
    SEMANTIC_COLOR_TEXT: 'SEMANTIC_COLOR_TEXT',
    SEMANTIC_COLOR_TEXT_ALT: 'SEMANTIC_COLOR_TEXT_ALT',
    SEMANTIC_COLOR_TEXT_ERROR: 'SEMANTIC_COLOR_TEXT_ERROR',
    SEMANTIC_COLOR_TEXT_HEADINGS: 'SEMANTIC_COLOR_TEXT_HEADINGS',
    // GLOBALS
    SEMANTIC_COLOR_ACCESSIBLE_BORDER: 'SEMANTIC_COLOR_ACCESSIBLE_BORDER',
    SEMANTIC_COLOR_DECORATIVE_BORDER: 'SEMANTIC_COLOR_DECORATIVE_BORDER',
    SEMANTIC_COLOR_FOCUS_HALO_INNER: 'SEMANTIC_COLOR_FOCUS_HALO_INNER',
    SEMANTIC_COLOR_FOCUS_HALO_OUTER: 'SEMANTIC_COLOR_FOCUS_HALO_OUTER',
    SEMANTIC_COLOR_HOVER_BG: 'SEMANTIC_COLOR_HOVER_BG',
};

const ACCENT_COLOR_PRIMARY = '#a33400';
const ACCENT_COLOR_SECONDARY = '#8500a3';
const ACCENT_COLOR_TERTIARY = '#a3006f';
const ERROR_COLOR = '#ae4652';
const PRIMARY_COLOR = '#006fa3';

export const SEMANTIC_COLOR_TOKEN_DEFAULTS = {
    // MAIN
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_BRAND]: PRIMARY_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_PRIMARY]: PRIMARY_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_SECONDARY]: '#346e89',
    // ACCENTS
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ACCENT_PRIMARY]:
        ACCENT_COLOR_PRIMARY,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ACCENT_SECONDARY]:
        ACCENT_COLOR_SECONDARY,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ACCENT_TERTIARY]:
        ACCENT_COLOR_TERTIARY,
    // STATUS
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_AFFIRMATIVE]: '#3d6d5b',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CAUTIONARY]: '#ebde69',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_DESTRUCTIVE]: ERROR_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ERROR]: ERROR_COLOR,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_INFO]: PRIMARY_COLOR,
    // CANVAS
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS]: CORE_COLOR_NEUTRAL_100,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS_ALT]:
        getNewColorByLightnessAdjustment(CORE_COLOR_NEUTRAL_SEED_DEFAULT, 95),
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS_BRAND]: '#00344d',
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CANVAS_BRAND_TEXT]:
        CORE_COLOR_NEUTRAL_90,
    // TEXT
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT]: CORE_COLOR_NEUTRAL_0,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT_ALT]: CORE_COLOR_NEUTRAL_30,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT_HEADINGS]:
        CORE_COLOR_NEUTRAL_0,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_TEXT_ERROR]: ERROR_COLOR,
    // UNIVERSAL
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ACCESSIBLE_BORDER]:
        CORE_COLOR_NEUTRAL_50,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_DECORATIVE_BORDER]:
        CORE_COLOR_NEUTRAL_80,
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_HOVER_BG]: CORE_COLOR_NEUTRAL_80,
};

export const STATUS_HUE_RANGES = {
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_AFFIRMATIVE]: {
        min: 140,
        max: 180,
    },
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_CAUTIONARY]: {
        min: 85,
        max: 100,
    },
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_ERROR]: {
        min: 0,
        max: 30,
    },
    [SEMANTIC_COLOR_TOKEN_NAMES.SEMANTIC_COLOR_INFO]: {
        min: 200,
        max: 240,
    },
};
