import { getNewColorByChangingLightness } from '@epr0t0type/bankai-lib-color-utils';
import { CORE_TOKEN_NAMES } from '../coreTokensConst';
import { LINK_TOKEN_NAMES } from '../linkTokensConst';
import { getAccessibleNeutralColor } from '../../../utils/helperUtils';
import { getCoreFontSizes } from '../../../utils/typographyUtils';

const {
    CORE_COLOR_ACCENT,
    CORE_COLOR_AFFIRMATIVE,
    CORE_COLOR_BRAND,
    CORE_COLOR_CANVAS,
    CORE_COLOR_CANVAS_ALT,
    CORE_COLOR_CAUTIONARY,
    CORE_COLOR_DESTRUCTIVE,
    CORE_COLOR_ERROR,
    CORE_COLOR_HEADINGS_TEXT,
    CORE_COLOR_INFO,
    CORE_COLOR_NEUTRAL_0,
    CORE_COLOR_NEUTRAL_10,
    CORE_COLOR_NEUTRAL_20,
    CORE_COLOR_NEUTRAL_30,
    CORE_COLOR_NEUTRAL_40,
    CORE_COLOR_NEUTRAL_50,
    CORE_COLOR_NEUTRAL_60,
    CORE_COLOR_NEUTRAL_70,
    CORE_COLOR_NEUTRAL_80,
    CORE_COLOR_NEUTRAL_90,
    CORE_COLOR_NEUTRAL_100,
    CORE_COLOR_PRIMARY,
    CORE_COLOR_SECONDARY,
    CORE_COLOR_TEXT,
    CORE_COLOR_TEXT_ALT,
    CORE_COLOR_TEXT_ERROR,
    CORE_COLOR_UNIVERSAL_ACCESSIBLE_BORDER,
    CORE_COLOR_UNIVERSAL_DECORATIVE_BORDER,
    // CORE_COLOR_UNIVERSAL_FOCUS_HALO,
    CORE_COLOR_UNIVERSAL_HOVER_BG,
    CORE_STATE_DISABLED_OPACITY,
    CORE_SYSTEM_SCALE,
    CORE_TYPOGRAPHY_FONT_FAMILY,
    CORE_TYPOGRAPHY_FONT_FAMILY_FALLBACK,
    CORE_TYPOGRAPHY_FONT_SIZE,
    CORE_TYPOGRAPHY_FONT_SIZE_SCALE,
    CORE_TYPOGRAPHY_FONT_WEIGHT,
    CORE_TYPOGRAPHY_FOOTNOTE_FONT_SIZE,
    CORE_TYPOGRAPHY_FOOTNOTE_MOBILE_FONT_SIZE,
    CORE_TYPOGRAPHY_FORM_INPUT_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_FONT_FAMILY,
    CORE_TYPOGRAPHY_HEADINGS_FONT_FAMILY_FALLBACK,
    CORE_TYPOGRAPHY_HEADINGS_FONT_STYLE,
    CORE_TYPOGRAPHY_HEADINGS_FONT_WEIGHT,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL1_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL1_MOBILE_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL2_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL2_MOBILE_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL3_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL3_MOBILE_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL4_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL4_MOBILE_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL5_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LEVEL5_MOBILE_FONT_SIZE,
    CORE_TYPOGRAPHY_HEADINGS_LINE_HEIGHT,
    CORE_TYPOGRAPHY_LINE_HEIGHT,
    CORE_TYPOGRAPHY_MOBILE_FONT_SIZE_SCALE,
    CORE_TYPOGRAPHY_SUB_TEXT_FONT_SIZE,
    CORE_TYPOGRAPHY_SUB_TEXT_MOBILE_FONT_SIZE,
} = CORE_TOKEN_NAMES;
const { LINK_TEXT_COLOR } = LINK_TOKEN_NAMES;

const neutralBaseColor = '#17191c';
export const CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS = {
    [CORE_COLOR_NEUTRAL_0]: '#000000',
    [CORE_COLOR_NEUTRAL_10]: getNewColorByChangingLightness(
        neutralBaseColor,
        10,
    ),
    [CORE_COLOR_NEUTRAL_20]: getNewColorByChangingLightness(
        neutralBaseColor,
        20,
    ),
    [CORE_COLOR_NEUTRAL_30]: getNewColorByChangingLightness(
        neutralBaseColor,
        30,
    ),
    [CORE_COLOR_NEUTRAL_40]: getNewColorByChangingLightness(
        neutralBaseColor,
        40,
    ),
    [CORE_COLOR_NEUTRAL_50]: getNewColorByChangingLightness(
        neutralBaseColor,
        50,
    ),
    [CORE_COLOR_NEUTRAL_60]: getNewColorByChangingLightness(
        neutralBaseColor,
        60,
    ),
    [CORE_COLOR_NEUTRAL_70]: getNewColorByChangingLightness(
        neutralBaseColor,
        70,
    ),
    [CORE_COLOR_NEUTRAL_80]: getNewColorByChangingLightness(
        neutralBaseColor,
        80,
    ),
    [CORE_COLOR_NEUTRAL_90]: getNewColorByChangingLightness(
        neutralBaseColor,
        90,
    ),
    [CORE_COLOR_NEUTRAL_100]: '#ffffff',
};

const ltPrimaryColor = '#008bcc';
const errorColor = '#cc3333';
const infoColor = '#1979e6';
const ltCanvasColor = CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_100;
const ltCanvasAltColor = getNewColorByChangingLightness(
    CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_90,
    95,
);
export const CORE_COLOR_LIGHT_THEME_TOKEN_DEFAULTS = {
    [CORE_COLOR_ACCENT]: '#362a3c',
    [CORE_COLOR_AFFIRMATIVE]: '#438946',
    [CORE_COLOR_BRAND]: ltPrimaryColor,
    [CORE_COLOR_CANVAS]: ltCanvasColor,
    [CORE_COLOR_CANVAS_ALT]: ltCanvasAltColor,
    [CORE_COLOR_CAUTIONARY]: '#fccf03',
    [CORE_COLOR_DESTRUCTIVE]: errorColor,
    [CORE_COLOR_ERROR]: errorColor,
    [CORE_COLOR_HEADINGS_TEXT]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_0,
    [CORE_COLOR_INFO]: infoColor,
    ...CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS,
    [CORE_COLOR_PRIMARY]: ltPrimaryColor,
    [CORE_COLOR_SECONDARY]: '#397a93',
    [CORE_COLOR_TEXT]: CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_0,
    [CORE_COLOR_TEXT_ALT]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_30,
    [CORE_COLOR_TEXT_ERROR]: errorColor,
    [CORE_COLOR_UNIVERSAL_DECORATIVE_BORDER]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_80,
    [CORE_COLOR_UNIVERSAL_ACCESSIBLE_BORDER]: getAccessibleNeutralColor(
        ltCanvasColor,
        ltCanvasAltColor,
    ),
    [CORE_COLOR_UNIVERSAL_HOVER_BG]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_90,
    [LINK_TEXT_COLOR]: '#1461b8',
};

const dtPrimaryColor = '#00aeff';
const dtCanvasColor = CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_10;
const dtCanvasColorAlt = getNewColorByChangingLightness(
    CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_20,
    15,
);

export const CORE_COLOR_DARK_THEME_TOKEN_DEFAULTS = {
    [CORE_COLOR_ACCENT]: '#876996',
    [CORE_COLOR_AFFIRMATIVE]: '#54ab58',
    [CORE_COLOR_BRAND]: dtPrimaryColor,
    [CORE_COLOR_CANVAS]: dtCanvasColor,
    [CORE_COLOR_CANVAS_ALT]: dtCanvasColorAlt,
    [CORE_COLOR_CAUTIONARY]: '#fccf03',
    [CORE_COLOR_DESTRUCTIVE]: errorColor,
    [CORE_COLOR_ERROR]: errorColor,
    [CORE_COLOR_HEADINGS_TEXT]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_100,
    [CORE_COLOR_INFO]: infoColor,
    ...CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS,
    [CORE_COLOR_PRIMARY]: dtPrimaryColor,
    [CORE_COLOR_SECONDARY]: '#4798b8',
    [CORE_COLOR_TEXT]: CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_100,
    [CORE_COLOR_TEXT_ALT]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_60,
    [CORE_COLOR_TEXT_ERROR]: errorColor,
    [CORE_COLOR_UNIVERSAL_ACCESSIBLE_BORDER]: getAccessibleNeutralColor(
        dtCanvasColor,
        dtCanvasColorAlt,
    ),
    [CORE_COLOR_UNIVERSAL_DECORATIVE_BORDER]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_30,
    [CORE_COLOR_UNIVERSAL_HOVER_BG]:
        CORE_COLOR_NEUTRAL_TOKEN_DEFAULTS.CORE_COLOR_NEUTRAL_20,
    [LINK_TEXT_COLOR]: '#4794eb',
};

export const MOBILE_FONT_SCALE = 1.125;
export const WEB_FONT_SCALE = 1.2;

const baseSize = 16;
const systemScale = 4;
const mobileFontSizes = getCoreFontSizes({
    baseSize,
    scale: MOBILE_FONT_SCALE,
});
const webFontSizes = getCoreFontSizes({ baseSize, scale: WEB_FONT_SCALE });
const fallbackFont = 'sans-serif';
export const CORE_STYLE_TOKEN_DEFAULTS = {
    [CORE_SYSTEM_SCALE]: systemScale,
    [CORE_STATE_DISABLED_OPACITY]: 0.3,
    [CORE_TYPOGRAPHY_FONT_FAMILY]: 'Bankai UI Body',
    [CORE_TYPOGRAPHY_FONT_FAMILY_FALLBACK]: fallbackFont,
    [CORE_TYPOGRAPHY_FONT_SIZE]: baseSize,
    [CORE_TYPOGRAPHY_FONT_SIZE_SCALE]: WEB_FONT_SCALE,
    [CORE_TYPOGRAPHY_FONT_WEIGHT]: 'normal',
    [CORE_TYPOGRAPHY_FOOTNOTE_FONT_SIZE]: webFontSizes.footnote,
    [CORE_TYPOGRAPHY_FOOTNOTE_MOBILE_FONT_SIZE]: mobileFontSizes.footnote,
    [CORE_TYPOGRAPHY_FORM_INPUT_FONT_SIZE]: webFontSizes.formInput,
    [CORE_TYPOGRAPHY_HEADINGS_FONT_FAMILY]: 'Bankai UI Headings',
    [CORE_TYPOGRAPHY_HEADINGS_FONT_FAMILY_FALLBACK]: fallbackFont,
    [CORE_TYPOGRAPHY_HEADINGS_FONT_STYLE]: 'normal',
    [CORE_TYPOGRAPHY_HEADINGS_FONT_WEIGHT]: 'bold',
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL1_FONT_SIZE]: webFontSizes.h1,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL1_MOBILE_FONT_SIZE]: mobileFontSizes.h1,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL2_FONT_SIZE]: webFontSizes.h2,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL2_MOBILE_FONT_SIZE]: mobileFontSizes.h2,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL3_FONT_SIZE]: webFontSizes.h3,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL3_MOBILE_FONT_SIZE]: mobileFontSizes.h3,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL4_FONT_SIZE]: webFontSizes.h4,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL4_MOBILE_FONT_SIZE]: mobileFontSizes.h4,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL5_FONT_SIZE]: webFontSizes.h5,
    [CORE_TYPOGRAPHY_HEADINGS_LEVEL5_MOBILE_FONT_SIZE]: mobileFontSizes.h5,
    [CORE_TYPOGRAPHY_HEADINGS_LINE_HEIGHT]: 1.2,
    [CORE_TYPOGRAPHY_LINE_HEIGHT]: 1.4,
    [CORE_TYPOGRAPHY_MOBILE_FONT_SIZE_SCALE]: MOBILE_FONT_SCALE,
    [CORE_TYPOGRAPHY_SUB_TEXT_FONT_SIZE]: webFontSizes.subText,
    [CORE_TYPOGRAPHY_SUB_TEXT_MOBILE_FONT_SIZE]: mobileFontSizes.subText,
};

export const getThemeDefaults = (isDarkMode) => {
    return isDarkMode
        ? CORE_COLOR_DARK_THEME_TOKEN_DEFAULTS
        : CORE_COLOR_LIGHT_THEME_TOKEN_DEFAULTS;
};
