const BOUNCE = 'BOUNCE';
const FADE = 'FADE';
const PULSE = 'PULSE';
const PULSE_FADE = 'PULSE_FADE';

export const LOADING_BARS_VARIANTS = {
    BOUNCE,
    FADE,
    FREQUENCY: 'FREQUENCY',
    // DRAW_THE_LINE: 'DRAW_THE_LINE',
    PULSE,
    PULSE_FADE,
};

export const LOADING_DOTS_VARIANTS = {
    BOUNCE,
    FADE,
    FADE_COMPACT: 'FADE_COMPACT',
    PULSE,
    PULSE_COMPACT: 'PULSE_COMPACT',
    PULSE_FADE,
    PULSE_FADE_COMPACT: 'PULSE_FADE_COMPACT',
    WORM: 'WORM',
};

export const LOADING_SPHERES_VARIANTS = {
    ALTERNATING_PULSE: 'ALTERNATING_PULSE',
    RIPPLES: 'RIPPLES',
    RIPPLES_OUTLINE: 'RIPPLES_OUTLINE',
};

export const LOADING_SPINNERS_VARIANTS = {
    ARCS: 'ARCS',
    CIRCULAR: 'CIRCULAR',
    CIRCULAR_DOTTED: 'CIRCULAR_DOTTED',
    CIRCULAR_DUAL: 'CIRCULAR_DUAL',
    CUBE: 'CUBE',
    CYBER: 'CYBER',
    PIXIES: 'PIXIES',
    ORBIT: 'ORBIT',
    TRI_CUBE: 'TRI_CUBE',
};

export const LOADING_SQUARES_VARIANTS = {
    FADE,
    FOLDING_QUADS: 'FOLDING_QUADS',
    PULSE,
    PULSING_WAVE: 'PULSING_WAVE',
    PULSE_FADE,
};
