import { ORDINAL_CHAR } from './sharedConst';

// See https://date-fns.org/v2.22.1/docs/format for formatting specs.

export const DAY_OF_MONTH_CHAR = 'd';
export const DAY_OF_YEAR_CHAR = DAY_OF_MONTH_CHAR.toUpperCase();
export const DAY_OF_WEEK_FORMATTING_CHAR = 'E';

export const DAY_OF_MONTH = {
    DAY_OF_MONTH_NUMBER: DAY_OF_MONTH_CHAR,
    DAY_OF_MONTH_NUMBER_ORDINAL: `${DAY_OF_MONTH_CHAR}${ORDINAL_CHAR}`,
    DAY_OF_MONTH_NUMBER_LEADING_ZERO: `${DAY_OF_MONTH_CHAR}${DAY_OF_MONTH_CHAR}`,
};

export const DAY_OF_YEAR = {
    DAY_OF_YEAR_NUMBER: DAY_OF_YEAR_CHAR,
    DAY_OF_YEAR_NUMBER_ORDINAL: `${DAY_OF_YEAR_CHAR}${ORDINAL_CHAR}`,
    DAY_OF_YEAR_NUMBER_SINGLE_LEADING_ZERO: `${DAY_OF_YEAR_CHAR}${DAY_OF_YEAR_CHAR}`,
    DAY_OF_YEAR_NUMBER_DOUBLE_LEADING_ZERO: `${DAY_OF_YEAR_CHAR}${DAY_OF_YEAR_CHAR}${DAY_OF_YEAR_CHAR}`,
};

export const DAY_OF_WEEK_FORMATTING = {
    DAY_OF_WEEK_ABBREVIATED_ONE_CHAR: `${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}`,
    DAY_OF_WEEK_ABBREVIATED_THREE_CHARS: DAY_OF_WEEK_FORMATTING_CHAR,
    DAY_OF_WEEK_ABBREVIATED_TWO_CHARS: `${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}`,
    DAY_OF_WEEK_FULL_NAME: `${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}${DAY_OF_WEEK_FORMATTING_CHAR}`,
};
