import { ORDINAL_CHAR } from './sharedConst';

// See https://date-fns.org/v2.22.1/docs/format for formatting specs.

export const TIME_PERIOD_CHAR = 'a';
export const HOUR_BASE12_CHAR = 'h';
export const HOUR_BASE24_CHAR = HOUR_BASE12_CHAR.toUpperCase();
export const MINUTE_CHAR = 'm';
export const SECOND_CHAR = 's';

export const TIME_PERIOD = {
    TIME_PERIOD_UPPERCASE: TIME_PERIOD_CHAR,
    TIME_PERIOD_LOWERCASE: `${TIME_PERIOD_CHAR}${TIME_PERIOD_CHAR}${TIME_PERIOD_CHAR}`,
    TIME_PERIOD_ABBREVIATED_LOWERCASE: `${TIME_PERIOD_CHAR}${TIME_PERIOD_CHAR}${TIME_PERIOD_CHAR}${TIME_PERIOD_CHAR}`,
};

export const HOUR_BASE12 = {
    HOUR_BASE12_REGULAR: HOUR_BASE12_CHAR,
    HOUR_BASE12_ORDINAL: `${HOUR_BASE12_CHAR}${ORDINAL_CHAR}`,
    HOUR_BASE12_LEADING_ZERO: `${HOUR_BASE12_CHAR}${HOUR_BASE12_CHAR}`,
};

export const HOUR_BASE24 = {
    HOUR_BASE12_REGULAR: HOUR_BASE24_CHAR,
    HOUR_BASE12_ORDINAL: `${HOUR_BASE24_CHAR}${ORDINAL_CHAR}`,
    HOUR_BASE12_LEADING_ZERO: `${HOUR_BASE24_CHAR}${HOUR_BASE24_CHAR}`,
};

export const MINUTE = {
    MINUTE_REGULAR: MINUTE_CHAR,
    MINUTE_ORDINAL: `${MINUTE_CHAR}${ORDINAL_CHAR}`,
    MINUTE_LEADING_ZERO: `${MINUTE_CHAR}${MINUTE_CHAR}`,
};

export const SECOND = {
    SECOND_REGULAR: SECOND_CHAR,
    SECOND_ORDINAL: `${SECOND_CHAR}${ORDINAL_CHAR}`,
    SECOND_LEADING_ZERO: `${SECOND_CHAR}${SECOND_CHAR}`,
};
