export const UTILITY_DATA_TOKEN_NAMES = {
    // GENERAL
    UTILITY_COLOR_DATA_BREWER_AXIS: 'UTILITY_COLOR_DATA_BREWER_AXIS',
    UTILITY_COLOR_DATA_BREWER_CANVAS: 'UTILITY_COLOR_DATA_BREWER_CANVAS',
    UTILITY_COLOR_DATA_BREWER_GRID: 'UTILITY_COLOR_DATA_BREWER_GRID',
};

export const UTILITY_DATA_BREWER_TOKEN_NAMES = {
    // DIVERGING
    // - BRBG
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_01:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_01',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_02:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_02',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_03:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_03',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_04:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_04',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_05:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_05',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_06:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_06',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_07:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_07',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_08:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_08',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_09:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_09',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_10:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_10',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_11:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_BRBG_11',
    // - PIYG
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_01:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_01',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_02:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_02',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_03:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_03',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_04:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_04',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_05:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_05',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_06:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_06',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_07:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_07',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_08:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_08',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_09:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_09',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_10:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_10',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_11:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PIYG_11',
    // - PRGN
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_01:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_01',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_02:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_02',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_03:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_03',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_04:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_04',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_05:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_05',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_06:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_06',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_07:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_07',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_08:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_08',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_09:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_09',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_10:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_10',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_11:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PRGN_11',
    // - PUOR
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_01:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_01',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_02:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_02',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_03:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_03',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_04:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_04',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_05:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_05',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_06:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_06',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_07:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_07',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_08:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_08',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_09:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_09',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_10:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_10',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_11:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_PUOR_11',
    // - RDBU
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_01:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_01',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_02:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_02',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_03:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_03',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_04:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_04',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_05:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_05',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_06:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_06',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_07:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_07',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_08:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_08',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_09:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_09',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_10:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_10',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_11:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDBU_11',
    // - RDGY
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_01:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_01',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_02:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_02',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_03:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_03',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_04:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_04',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_05:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_05',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_06:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_06',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_07:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_07',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_08:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_08',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_09:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_09',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_10:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_10',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_11:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDGY_11',
    // - RDYLBU
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_01:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_01',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_02:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_02',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_03:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_03',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_04:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_04',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_05:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_05',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_06:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_06',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_07:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_07',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_08:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_08',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_09:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_09',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_10:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_10',
    UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_11:
        'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLBU_11',
    // - RDYLGN
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_01:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_01',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_02:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_02',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_03:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_03',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_04:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_04',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_05:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_05',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_06:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_06',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_07:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_07',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_08:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_08',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_09:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_09',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_10:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_10',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_11:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_RDYLGN_11',
    // - SPECTRAL
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_01:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_01',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_02:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_02',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_03:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_03',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_04:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_04',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_05:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_05',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_06:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_06',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_07:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_07',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_08:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_08',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_09:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_09',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_10:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_10',
    // UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_11:
    //     'UTILITY_COLOR_DATA_BREWER_DIVERGING_SPECTRAL_11',
    // QUALITATIVE
    // - ACCENT
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_01:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_01',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_02:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_02',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_03:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_ACCENT_08',
    // - DARK2
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_01:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_01',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_02:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_02',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_03:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_DARK2_08',
    // - PAIRED
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_01:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_01',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_02:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_02',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_03:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_03',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_04:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_08',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_09:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_09',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_10:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_10',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_11:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_11',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_12:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PAIRED_12',
    // - PASTEL1
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_01:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_01',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_02:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_02',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_03:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_08',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_09:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL1_09',
    // - PASTEL2
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_01:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_01',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_02:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_02',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_03:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_PASTEL2_08',
    //  - SET1
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_01:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_01',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_02:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_02',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_03:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_08',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_09:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET1_09',
    //  - SET2
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_01:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_01',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_02:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_02',
    UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_03:
        'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET2_08',
    //  - SET3
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_01:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_01',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_02:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_02',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_03:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_03',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_04:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_04',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_05:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_05',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_06:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_06',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_07:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_07',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_08:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_08',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_09:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_09',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_10:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_10',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_11:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_11',
    // UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_12:
    //     'UTILITY_COLOR_DATA_BREWER_QUALITATIVE_SET3_12',
    // SEQUENTIAL
    // - BLUES
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BLUES_09',
    // - GREENS
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREENS_09',
    // - GREYS
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GREYS_09',
    // - ORANGES
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORANGES_09',
    // - PURPLES
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURPLES_09',
    // - REDS
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_REDS_09',
    // - BUGN
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUGN_09',
    // - BUPU
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_BUPU_09',
    // - GNBU
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_GNBU_09',
    // - OrRd
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_ORRD_09',
    // - PUBU
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBU_09',
    // - PUBUGN
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PUBUGN_09',
    // - PURD
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_PURD_09',
    // - RDPU
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_RDPU_09',
    // - YLGN
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGN_09',
    // - YLGNBU
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLGNBU_09',
    // - YLORBR
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORBR_09',
    // - YLORRD
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_01:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_01',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_02:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_02',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_03:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_03',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_04:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_04',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_05:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_05',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_06:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_06',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_07:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_07',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_08:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_08',
    UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_09:
        'UTILITY_COLOR_DATA_BREWER_SEQUENTIAL_YLORRD_09',
};

// Colorblind-Friendly only as documented here: https://jakubnowosad.com/rcartocolor/
export const UTILITY_DATA_CARTO_COLOR_TOKEN_NAMES = {
    // DIVERGING
    // - ARMYROSE
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_ARMYROSE_07',
    // - EARTH
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_EARTH_07',
    // // - FALL
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_FALL_07',
    // - GEYSER
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_GEYSER_07',
    // // - TEALROSE
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEALROSE_07',
    // // - TEMPS
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TEMPS_07',
    // // - TROPIC
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_DIVERGING_TROPIC_07',

    // QUALITATIVE
    // // - ANTIQUE
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_07',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_08:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_08',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_09:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_09',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_10:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_10',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_11:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_11',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_12:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_ANTIQUE_12',
    // // - BOLD
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_07',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_08:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_08',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_09:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_09',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_10:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_10',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_11:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_11',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_12:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_BOLD_12',
    // // - PASTEL
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_07',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_08:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_08',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_09:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_09',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_10:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_10',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_11:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_11',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_12:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PASTEL_12',
    // // - PRISM
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_07',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_08:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_08',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_09:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_09',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_10:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_10',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_11:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_11',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_12:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_PRISM_12',
    // - SAFE
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_07',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_08:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_08',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_09:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_09',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_10:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_10',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_11:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_11',
    UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_12:
        'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_SAFE_12',
    // // - VIVID
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_01:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_01',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_02:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_02',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_03:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_03',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_04:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_04',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_05:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_05',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_06:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_06',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_07:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_07',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_08:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_08',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_09:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_09',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_10:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_10',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_11:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_11',
    // UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_12:
    //     'UTILITY_COLOR_DATA_CARTO_COLOR_QUALITATIVE_VIVID_12',

    // SEQUENTIAL
    // - BLUGRN
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUGRN_07',
    // - BLUYL
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BLUYL_07',
    // - BRWNYL
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BRWNYL_07',
    // - BURG
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURG_07',
    // - BURGYL
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_BURGYL_07',
    // - DARKMINT
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_DARKMINT_07',
    // - EMRLD
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_EMRLD_07',
    // - MAGENTA
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MAGENTA_07',
    // - MINT
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_MINT_07',
    // - ORYEL
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_ORYEL_07',
    // - PEACH
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PEACH_07',
    // - PINKYL
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PINKYL_07',
    // - PURP
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURP_07',
    // - PURPOR
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_PURPOR_07',
    // - REDOR
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_REDOR_07',
    // - SUNSET
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSET_07',
    // - SUNSETDARK
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_SUNSETDARK_07',
    // - TEAL
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEAL_07',
    // - TEALGRN
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_01:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_01',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_02:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_02',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_03:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_03',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_04:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_04',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_05:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_05',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_06:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_06',
    UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_07:
        'UTILITY_COLOR_DATA_CARTO_COLOR_SEQUENTIAL_TEALGRN_07',
};
