/* eslint-disable import/prefer-default-export */

export const UTILITY_DATA_TOKEN_NAMES = {
    // GENERAL
    UTILITY_COLOR_DATA_AXIS: 'UTILITY_COLOR_DATA_AXIS',
    UTILITY_COLOR_DATA_CANVAS: 'UTILITY_COLOR_DATA_CANVAS',
    UTILITY_COLOR_DATA_GRID: 'UTILITY_COLOR_DATA_GRID',
    // QUALITATIVE
    // - ACCENT
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_01:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_01',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_02:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_02',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_03:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_ACCENT_08',
    // - DARK2
    UTILITY_COLOR_DATA_QUALITATIVE_DARK2_01:
        'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_01',
    UTILITY_COLOR_DATA_QUALITATIVE_DARK2_02:
        'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_02',
    UTILITY_COLOR_DATA_QUALITATIVE_DARK2_03:
        'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_DARK2_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_DARK2_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_DARK2_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_DARK2_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_DARK2_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_DARK2_08',
    // - PAIRED
    UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_01:
        'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_01',
    UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_02:
        'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_02',
    UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_03:
        'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_03',
    UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_04:
        'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_08',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_09:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_09',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_10:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_10',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_11:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_11',
    // UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_12:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PAIRED_12',
    // - PASTEL1
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_01:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_01',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_02:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_02',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_03:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_08',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_09:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL1_09',
    // - PASTEL2
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_01:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_01',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_02:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_02',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_03:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_PASTEL2_08',
    //  - SET1
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_01:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_01',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_02:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_02',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_03:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_08',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET1_09:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET1_09',
    //  - SET2
    UTILITY_COLOR_DATA_QUALITATIVE_SET2_01:
        'UTILITY_COLOR_DATA_QUALITATIVE_SET2_01',
    UTILITY_COLOR_DATA_QUALITATIVE_SET2_02:
        'UTILITY_COLOR_DATA_QUALITATIVE_SET2_02',
    UTILITY_COLOR_DATA_QUALITATIVE_SET2_03:
        'UTILITY_COLOR_DATA_QUALITATIVE_SET2_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET2_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET2_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET2_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET2_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET2_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET2_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET2_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET2_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET2_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET2_08',
    //  - SET3
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_01:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_01',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_02:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_02',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_03:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_03',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_04:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_04',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_05:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_05',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_06:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_06',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_07:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_07',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_08:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_08',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_09:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_09',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_10:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_10',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_11:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_11',
    // UTILITY_COLOR_DATA_QUALITATIVE_SET3_12:
    //     'UTILITY_COLOR_DATA_QUALITATIVE_SET3_12',
    // SEQUENTIAL
    // - BLUES
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BLUES_09',
    // - GREENS
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREENS_09',
    // - GREYS
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GREYS_09',
    // - ORANGES
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORANGES_09',
    // - PURPLES
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURPLES_09',
    // - REDS
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_REDS_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_REDS_09',
    // - BUGN
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUGN_09',
    // - BUPU
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_BUPU_09',
    // - GNBU
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_GNBU_09',
    // - OrRd
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_ORRD_09',
    // - PUBU
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBU_09',
    // - PUBUGN
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PUBUGN_09',
    // - PURD
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_PURD_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_PURD_09',
    // - RDPU
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_RDPU_09',
    // - YLGN
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGN_09',
    // - YLGNBU
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLGNBU_09',
    // - YLORBR
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORBR_09',
    // - YLORRD
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_01:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_01',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_02:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_02',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_03:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_03',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_04:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_04',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_05:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_05',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_06:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_06',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_07:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_07',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_08:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_08',
    UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_09:
        'UTILITY_COLOR_DATA_SEQUENTIAL_YLORRD_09',
    // DIVERGING
    // - BRBG
    UTILITY_COLOR_DATA_DIVERGING_BRBG_01:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_01',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_02:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_02',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_03:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_03',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_04:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_04',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_05:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_05',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_06:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_06',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_07:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_07',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_08:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_08',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_09:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_09',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_10:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_10',
    UTILITY_COLOR_DATA_DIVERGING_BRBG_11:
        'UTILITY_COLOR_DATA_DIVERGING_BRBG_11',
    // - PIYG
    UTILITY_COLOR_DATA_DIVERGING_PIYG_01:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_01',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_02:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_02',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_03:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_03',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_04:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_04',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_05:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_05',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_06:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_06',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_07:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_07',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_08:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_08',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_09:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_09',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_10:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_10',
    UTILITY_COLOR_DATA_DIVERGING_PIYG_11:
        'UTILITY_COLOR_DATA_DIVERGING_PIYG_11',
    // - PRGN
    UTILITY_COLOR_DATA_DIVERGING_PRGN_01:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_01',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_02:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_02',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_03:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_03',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_04:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_04',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_05:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_05',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_06:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_06',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_07:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_07',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_08:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_08',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_09:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_09',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_10:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_10',
    UTILITY_COLOR_DATA_DIVERGING_PRGN_11:
        'UTILITY_COLOR_DATA_DIVERGING_PRGN_11',
    // - PUOR
    UTILITY_COLOR_DATA_DIVERGING_PUOR_01:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_01',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_02:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_02',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_03:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_03',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_04:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_04',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_05:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_05',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_06:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_06',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_07:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_07',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_08:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_08',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_09:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_09',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_10:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_10',
    UTILITY_COLOR_DATA_DIVERGING_PUOR_11:
        'UTILITY_COLOR_DATA_DIVERGING_PUOR_11',
    // - RDBU
    UTILITY_COLOR_DATA_DIVERGING_RDBU_01:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_01',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_02:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_02',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_03:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_03',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_04:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_04',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_05:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_05',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_06:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_06',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_07:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_07',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_08:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_08',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_09:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_09',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_10:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_10',
    UTILITY_COLOR_DATA_DIVERGING_RDBU_11:
        'UTILITY_COLOR_DATA_DIVERGING_RDBU_11',
    // - RDGY
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_01:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_01',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_02:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_02',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_03:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_03',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_04:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_04',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_05:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_05',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_06:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_06',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_07:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_07',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_08:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_08',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_09:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_09',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_10:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_10',
    // UTILITY_COLOR_DATA_DIVERGING_RDGY_11:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDGY_11',
    // - RDYLBU
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_01:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_01',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_02:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_02',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_03:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_03',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_04:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_04',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_05:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_05',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_06:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_06',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_07:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_07',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_08:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_08',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_09:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_09',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_10:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_10',
    UTILITY_COLOR_DATA_DIVERGING_RDYLBU_11:
        'UTILITY_COLOR_DATA_DIVERGING_RDYLBU_11',
    // - RDYLGN
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_01:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_01',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_02:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_02',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_03:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_03',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_04:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_04',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_05:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_05',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_06:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_06',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_07:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_07',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_08:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_08',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_09:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_09',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_10:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_10',
    // UTILITY_COLOR_DATA_DIVERGING_RDYLGN_11:
    //     'UTILITY_COLOR_DATA_DIVERGING_RDYLGN_11',
    // - SPECTRAL
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_01:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_01',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_02:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_02',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_03:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_03',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_04:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_04',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_05:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_05',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_06:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_06',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_07:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_07',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_08:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_08',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_09:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_09',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_10:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_10',
    // UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_11:
    //     'UTILITY_COLOR_DATA_DIVERGING_SPECTRAL_11',
};
