export const ACCORDION_COLOR_TOKEN_NAMES = {
    ACCORDION_BORDER_COLOR: 'ACCORDION_BORDER_COLOR',
    ACCORDION_BG_COLOR: 'ACCORDION_BG_COLOR',
    ACCORDION_TRIGGER_TEXT_COLOR: 'ACCORDION_TRIGGER_TEXT_COLOR',
    ACCORDION_TRIGGER_HOVER_BG_COLOR: 'ACCORDION_TRIGGER_HOVER_BG_COLOR',
    ACCORDION_TRIGGER_HOVER_TEXT_COLOR: 'ACCORDION_TRIGGER_HOVER_TEXT_COLOR',
};

export const ACCORDION_STYLE_TOKEN_NAMES = {
    ACCORDION_BORDER_RADIUS: 'ACCORDION_BORDER_RADIUS',
    ACCORDION_BORDER_WIDTH: 'ACCORDION_BORDER_WIDTH',
};

export const ACCORDION_TOKEN_NAMES = {
    ...ACCORDION_COLOR_TOKEN_NAMES,
    ...ACCORDION_STYLE_TOKEN_NAMES,
};
