export const AVATAR_COLOR_TOKEN_NAMES = {
    AVATAR_BG_COLOR: 'AVATAR_BG_COLOR',
    AVATAR_BORDER_COLOR: 'AVATAR_BORDER_COLOR',
    AVATAR_TEXT_COLOR: 'AVATAR_TEXT_COLOR',
};

export const AVATAR_TOKEN_NAMES = {
    ...AVATAR_COLOR_TOKEN_NAMES,
};
