export const BADGE_COLOR_TOKEN_NAMES = {
    BADGE_BG_COLOR: 'BADGE_BG_COLOR',
    BADGE_TEXT_COLOR: 'BADGE_TEXT_COLOR',
    // Affirmative
    BADGE_AFFIRMATIVE_BG_COLOR: 'BADGE_AFFIRMATIVE_BG_COLOR',
    BADGE_AFFIRMATIVE_TEXT_COLOR: 'BADGE_AFFIRMATIVE_TEXT_COLOR',
    // Cautionary
    BADGE_CAUTIONARY_BG_COLOR: 'BADGE_CAUTIONARY_BG_COLOR',
    BADGE_CAUTIONARY_TEXT_COLOR: 'BADGE_CAUTIONARY_TEXT_COLOR',
    // Error
    BADGE_ERROR_BG_COLOR: 'BADGE_ERROR_BG_COLOR',
    BADGE_ERROR_TEXT_COLOR: 'BADGE_ERROR_TEXT_COLOR',
    // Info
    BADGE_INFO_BG_COLOR: 'BADGE_INFO_BG_COLOR',
    BADGE_INFO_TEXT_COLOR: 'BADGE_INFO_TEXT_COLOR',
};

export const BADGE_STYLE_TOKEN_NAMES = {
    BADGE_BORDER_RADIUS: 'BADGE_BORDER_RADIUS',
};

export const BADGE_TOKEN_NAMES = {
    ...BADGE_COLOR_TOKEN_NAMES,
    ...BADGE_STYLE_TOKEN_NAMES,
};
