export const BTN_PRIMARY_COLOR_TOKEN_NAMES = {
    BTN_PRIMARY_ACTIVE_BG_COLOR: 'BTN_PRIMARY_ACTIVE_BG_COLOR',
    BTN_PRIMARY_ACTIVE_BORDER_COLOR: 'BTN_PRIMARY_ACTIVE_BORDER_COLOR',
    BTN_PRIMARY_ACTIVE_TEXT_COLOR: 'BTN_PRIMARY_ACTIVE_TEXT_COLOR',
    BTN_PRIMARY_BG_COLOR: 'BTN_PRIMARY_BG_COLOR',
    BTN_PRIMARY_BORDER_COLOR: 'BTN_PRIMARY_BORDER_COLOR',
    BTN_PRIMARY_TEXT_COLOR: 'BTN_PRIMARY_TEXT_COLOR',
    BTN_PRIMARY_FOCUS_HALO_COLOR: 'BTN_PRIMARY_FOCUS_HALO_COLOR',
    BTN_PRIMARY_HOVER_BG_COLOR: 'BTN_PRIMARY_HOVER_BG_COLOR',
    BTN_PRIMARY_HOVER_BORDER_COLOR: 'BTN_PRIMARY_HOVER_BORDER_COLOR',
    BTN_PRIMARY_HOVER_TEXT_COLOR: 'BTN_PRIMARY_HOVER_TEXT_COLOR',
    BTN_SPLIT_PRIMARY_BORDER_COLOR: 'BTN_SPLIT_PRIMARY_BORDER_COLOR',
};

export const BTN_SECONDARY_COLOR_TOKEN_NAMES = {
    BTN_SECONDARY_ACTIVE_BG_COLOR: 'BTN_SECONDARY_ACTIVE_BG_COLOR',
    BTN_SECONDARY_ACTIVE_BORDER_COLOR: 'BTN_SECONDARY_ACTIVE_BORDER_COLOR',
    BTN_SECONDARY_ACTIVE_TEXT_COLOR: 'BTN_SECONDARY_ACTIVE_TEXT_COLOR',
    BTN_SECONDARY_BG_COLOR: 'BTN_SECONDARY_BG_COLOR',
    BTN_SECONDARY_BORDER_COLOR: 'BTN_SECONDARY_BORDER_COLOR',
    BTN_SECONDARY_TEXT_COLOR: 'BTN_SECONDARY_TEXT_COLOR',
    BTN_SECONDARY_FOCUS_HALO_COLOR: 'BTN_SECONDARY_FOCUS_HALO_COLOR',
    BTN_SECONDARY_HOVER_BG_COLOR: 'BTN_SECONDARY_HOVER_BG_COLOR',
    BTN_SECONDARY_HOVER_BORDER_COLOR: 'BTN_SECONDARY_HOVER_BORDER_COLOR',
    BTN_SECONDARY_HOVER_TEXT_COLOR: 'BTN_SECONDARY_HOVER_TEXT_COLOR',
    BTN_SPLIT_SECONDARY_BORDER_COLOR: 'BTN_SPLIT_SECONDARY_BORDER_COLOR',
};

export const BTN_PRIMARY_DESTRUCTIVE_COLOR_TOKEN_NAMES = {
    BTN_PRIMARY_DESTRUCTIVE_ACTIVE_BG_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_ACTIVE_BG_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_ACTIVE_BORDER_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_ACTIVE_BORDER_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_ACTIVE_TEXT_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_ACTIVE_TEXT_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_BG_COLOR: 'BTN_PRIMARY_DESTRUCTIVE_BG_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_BORDER_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_BORDER_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_TEXT_COLOR: 'BTN_PRIMARY_DESTRUCTIVE_TEXT_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_FOCUS_HALO_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_FOCUS_HALO_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_HOVER_BG_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_HOVER_BG_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_HOVER_BORDER_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_HOVER_BORDER_COLOR',
    BTN_PRIMARY_DESTRUCTIVE_HOVER_TEXT_COLOR:
        'BTN_PRIMARY_DESTRUCTIVE_HOVER_TEXT_COLOR',
    BTN_SPLIT_PRIMARY_DESTRUCTIVE_BORDER_COLOR:
        'BTN_SPLIT_PRIMARY_DESTRUCTIVE_BORDER_COLOR',
};

export const BTN_SECONDARY_DESTRUCTIVE_COLOR_TOKEN_NAMES = {
    BTN_SECONDARY_DESTRUCTIVE_ACTIVE_BG_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_ACTIVE_BG_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_ACTIVE_BORDER_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_ACTIVE_BORDER_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_ACTIVE_TEXT_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_ACTIVE_TEXT_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_BG_COLOR: 'BTN_SECONDARY_DESTRUCTIVE_BG_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_BORDER_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_BORDER_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_TEXT_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_TEXT_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_FOCUS_HALO_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_FOCUS_HALO_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_HOVER_BG_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_HOVER_BG_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_HOVER_BORDER_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_HOVER_BORDER_COLOR',
    BTN_SECONDARY_DESTRUCTIVE_HOVER_TEXT_COLOR:
        'BTN_SECONDARY_DESTRUCTIVE_HOVER_TEXT_COLOR',
    BTN_SPLIT_SECONDARY_DESTRUCTIVE_BORDER_COLOR:
        'BTN_SPLIT_SECONDARY_DESTRUCTIVE_BORDER_COLOR',
};

export const BTN_COLOR_TOKEN_NAMES = {
    ...BTN_PRIMARY_COLOR_TOKEN_NAMES,
    ...BTN_SECONDARY_COLOR_TOKEN_NAMES,
    ...BTN_PRIMARY_DESTRUCTIVE_COLOR_TOKEN_NAMES,
    ...BTN_SECONDARY_DESTRUCTIVE_COLOR_TOKEN_NAMES,
};

export const BTN_STYLE_TOKEN_NAMES = {
    BTN_BORDER_RADIUS: 'BTN_BORDER_RADIUS',
    BTN_BORDER_WIDTH: 'BTN_BORDER_WIDTH',
    BTN_FONT_WEIGHT: 'BTN_FONT_WEIGHT',
};

export const DIALOG_ACTION_STYLE_TOKEN_NAMES = {
    DIALOG_ACTION_BORDER_RADIUS: 'DIALOG_ACTION_BORDER_RADIUS',
};

export const BTN_TOKEN_NAMES = {
    ...BTN_COLOR_TOKEN_NAMES,
    ...BTN_STYLE_TOKEN_NAMES,
    ...DIALOG_ACTION_STYLE_TOKEN_NAMES,
};
