export const CALLOUT_DEFAULT_COLOR_TOKEN_NAMES = {
    CALLOUT_ICON_COLOR: 'CALLOUT_ICON_COLOR',
};

export const CALLOUT_AFFIRMATIVE_COLOR_TOKEN_NAMES = {
    CALLOUT_AFFIRMATIVE_ICON_COLOR: 'CALLOUT_AFFIRMATIVE_ICON_COLOR',
};

export const CALLOUT_CAUTIONARY_COLOR_TOKEN_NAMES = {
    CALLOUT_CAUTIONARY_ICON_COLOR: 'CALLOUT_CAUTIONARY_ICON_COLOR',
};

export const CALLOUT_ERROR_COLOR_TOKEN_NAMES = {
    CALLOUT_ERROR_ICON_COLOR: 'CALLOUT_ERROR_ICON_COLOR',
};

export const CALLOUT_INFO_COLOR_TOKEN_NAMES = {
    CALLOUT_INFO_ICON_COLOR: 'CALLOUT_INFO_ICON_COLOR',
};

export const CALLOUT_BANNER_DEFAULT_COLOR_TOKEN_NAMES = {
    CALLOUT_BANNER_BG_COLOR: 'CALLOUT_BANNER_BG_COLOR',
    CALLOUT_BANNER_ICON_COLOR: 'CALLOUT_BANNER_ICON_COLOR',
    CALLOUT_BANNER_TEXT_COLOR: 'CALLOUT_BANNER_TEXT_COLOR',
};

export const CALLOUT_BANNER_AFFIRMATIVE_COLOR_TOKEN_NAMES = {
    CALLOUT_BANNER_AFFIRMATIVE_BG_COLOR: 'CALLOUT_BANNER_AFFIRMATIVE_BG_COLOR',
    CALLOUT_BANNER_AFFIRMATIVE_ICON_COLOR:
        'CALLOUT_BANNER_AFFIRMATIVE_ICON_COLOR',
    CALLOUT_BANNER_AFFIRMATIVE_TEXT_COLOR:
        'CALLOUT_BANNER_AFFIRMATIVE_TEXT_COLOR',
};

export const CALLOUT_BANNER_CAUTIONARY_COLOR_TOKEN_NAMES = {
    CALLOUT_BANNER_CAUTIONARY_BG_COLOR: 'CALLOUT_BANNER_CAUTIONARY_BG_COLOR',
    CALLOUT_BANNER_CAUTIONARY_ICON_COLOR:
        'CALLOUT_BANNER_CAUTIONARY_ICON_COLOR',
    CALLOUT_BANNER_CAUTIONARY_TEXT_COLOR:
        'CALLOUT_BANNER_CAUTIONARY_TEXT_COLOR',
};

export const CALLOUT_BANNER_ERROR_COLOR_TOKEN_NAMES = {
    CALLOUT_BANNER_ERROR_BG_COLOR: 'CALLOUT_BANNER_ERROR_BG_COLOR',
    CALLOUT_BANNER_ERROR_ICON_COLOR: 'CALLOUT_BANNER_ERROR_ICON_COLOR',
    CALLOUT_BANNER_ERROR_TEXT_COLOR: 'CALLOUT_BANNER_ERROR_TEXT_COLOR',
};

export const CALLOUT_BANNER_INFO_COLOR_TOKEN_NAMES = {
    CALLOUT_BANNER_INFO_BG_COLOR: 'CALLOUT_BANNER_INFO_BG_COLOR',
    CALLOUT_BANNER_INFO_ICON_COLOR: 'CALLOUT_BANNER_INFO_ICON_COLOR',
    CALLOUT_BANNER_INFO_TEXT_COLOR: 'CALLOUT_BANNER_INFO_TEXT_COLOR',
};

export const CALLOUT_COLOR_TOKEN_NAMES = {
    ...CALLOUT_DEFAULT_COLOR_TOKEN_NAMES,
    ...CALLOUT_AFFIRMATIVE_COLOR_TOKEN_NAMES,
    ...CALLOUT_BANNER_AFFIRMATIVE_COLOR_TOKEN_NAMES,
    ...CALLOUT_BANNER_CAUTIONARY_COLOR_TOKEN_NAMES,
    ...CALLOUT_BANNER_DEFAULT_COLOR_TOKEN_NAMES,
    ...CALLOUT_BANNER_ERROR_COLOR_TOKEN_NAMES,
    ...CALLOUT_BANNER_INFO_COLOR_TOKEN_NAMES,
    ...CALLOUT_CAUTIONARY_COLOR_TOKEN_NAMES,
    ...CALLOUT_ERROR_COLOR_TOKEN_NAMES,
    ...CALLOUT_INFO_COLOR_TOKEN_NAMES,
};

export const CALLOUT_STYLE_TOKEN_NAMES = {
    CALLOUT_BANNER_BORDER_RADIUS: 'CALLOUT_BANNER_BORDER_RADIUS',
};

export const CALLOUT_TOKEN_NAMES = {
    ...CALLOUT_COLOR_TOKEN_NAMES,
    ...CALLOUT_STYLE_TOKEN_NAMES,
};
