export const FORM_STATE_COLOR_TOKEN_NAMES = {
    FORM_CHECKED_ACCENT_COLOR: 'FORM_CHECKED_ACCENT_COLOR',
    FORM_CHECKED_FOCUS_HALO_COLOR: 'FORM_CHECKED_FOCUS_HALO_COLOR',
    FORM_CHECKED_ACCENT_COMPLIMENT_COLOR:
        'FORM_CHECKED_ACCENT_COMPLIMENT_COLOR',
};

export const FORM_DATE_PICKER_COLOR_TOKEN_NAMES = {
    FORM_DATE_PICKER_OFF_RANGE_TEXT_COLOR:
        'FORM_DATE_PICKER_OFF_RANGE_TEXT_COLOR',
};

export const FORM_DND_FILE_UPLOADER_COLOR_TOKEN_NAMES = {
    FORM_DND_FILE_UPLOADER_HOVER_BG_COLOR:
        'FORM_DND_FILE_UPLOADER_HOVER_BG_COLOR',
    FORM_DND_FILE_UPLOADER_HOVER_BORDER_COLOR:
        'FORM_DND_FILE_UPLOADER_HOVER_BORDER_COLOR',
    FORM_DND_FILE_UPLOADER_HOVER_TEXT_COLOR:
        'FORM_DND_FILE_UPLOADER_HOVER_TEXT_COLOR',
    FORM_DND_FILE_UPLOADER_REJECTED_BG_COLOR:
        'FORM_DND_FILE_UPLOADER_REJECTED_BG_COLOR',
    FORM_DND_FILE_UPLOADER_REJECTED_BORDER_COLOR:
        'FORM_DND_FILE_UPLOADER_REJECTED_BORDER_COLOR',
    FORM_DND_FILE_UPLOADER_REJECTED_TEXT_COLOR:
        'FORM_DND_FILE_UPLOADER_REJECTED_TEXT_COLOR',
};

export const FORM_INPUT_COLOR_TOKEN_NAMES = {
    FORM_INPUT_BG_COLOR: 'FORM_INPUT_BG_COLOR',
    FORM_INPUT_DISABLED_BG_COLOR: 'FORM_INPUT_DISABLED_BG_COLOR',
    FORM_INPUT_DISABLED_PLACEHOLDER_TEXT_COLOR:
        'FORM_INPUT_DISABLED_PLACEHOLDER_TEXT_COLOR',
    FORM_INPUT_ERROR_BG_COLOR: 'FORM_INPUT_ERROR_BG_COLOR',
    FORM_INPUT_ERROR_BORDER_COLOR: 'FORM_INPUT_ERROR_BORDER_COLOR',
    FORM_INPUT_ERROR_FOCUS_HALO_COLOR: 'FORM_INPUT_ERROR_FOCUS_HALO_COLOR',
    FORM_INPUT_ERROR_PLACEHOLDER_TEXT_COLOR:
        'FORM_INPUT_ERROR_PLACEHOLDER_TEXT_COLOR',
    FORM_INPUT_FOCUS_BORDER_COLOR: 'FORM_INPUT_FOCUS_BORDER_COLOR',
    FORM_INPUT_FOCUS_HALO_COLOR: 'FORM_INPUT_FOCUS_HALO_COLOR',
    FORM_INPUT_TEXT_COLOR: 'FORM_INPUT_TEXT_COLOR',
    FORM_INPUT_PLACEHOLDER_TEXT_COLOR: 'FORM_INPUT_PLACEHOLDER_TEXT_COLOR',
};

export const FORM_MENU_COLOR_TOKEN_NAMES = {
    FORM_MENU_SELECTED_BG_COLOR: 'FORM_MENU_SELECTED_BG_COLOR',
    FORM_MENU_SELECTED_FOCUS_BG_COLOR: 'FORM_MENU_SELECTED_FOCUS_BG_COLOR',
    FORM_MENU_SELECTED_FOCUS_TEXT_COLOR: 'FORM_MENU_SELECTED_FOCUS_TEXT_COLOR',
    FORM_MENU_SELECTED_TEXT_COLOR: 'FORM_MENU_SELECTED_TEXT_COLOR',
};

export const FORM_PILL_COLOR_TOKEN_NAMES = {
    FORM_PILL_BG_COLOR: 'FORM_PILL_BG_COLOR',
    FORM_PILL_TEXT_COLOR: 'FORM_PILL_TEXT_COLOR',
};

export const FORM_TOGGLE_SWITCH_COLOR_TOKEN_NAMES = {
    FORM_TOGGLE_SWITCH_BUSY_ICON_COLOR: 'FORM_TOGGLE_SWITCH_BUSY_ICON_COLOR',
    FORM_TOGGLE_SWITCH_KNOB_COLOR: 'FORM_TOGGLE_SWITCH_KNOB_COLOR',
    FORM_TOGGLE_SWITCH_KNOB_BORDER_COLOR:
        'FORM_TOGGLE_SWITCH_KNOB_BORDER_COLOR',
    FORM_TOGGLE_SWITCH_TRACK_COLOR: 'FORM_TOGGLE_SWITCH_TRACK_COLOR',
    FORM_TOGGLE_SWITCH_TRACK_HOVER_COLOR:
        'FORM_TOGGLE_SWITCH_TRACK_HOVER_COLOR',
    FORM_TOGGLE_SWITCH_ON_BUSY_ICON_COLOR:
        'FORM_TOGGLE_SWITCH_ON_BUSY_ICON_COLOR',
    FORM_TOGGLE_SWITCH_ON_FOCUS_HALO_COLOR:
        'FORM_TOGGLE_SWITCH_ON_FOCUS_HALO_COLOR',
    FORM_TOGGLE_SWITCH_ON_HOVER_TRACK_COLOR:
        'FORM_TOGGLE_SWITCH_ON_HOVER_TRACK_COLOR',
    FORM_TOGGLE_SWITCH_ON_KNOB_COLOR: 'FORM_TOGGLE_SWITCH_ON_KNOB_COLOR',
    FORM_TOGGLE_SWITCH_ON_TRACK_COLOR: 'FORM_TOGGLE_SWITCH_ON_TRACK_COLOR',
};

export const FORM_COLOR_TOKEN_NAMES = {
    ...FORM_STATE_COLOR_TOKEN_NAMES,
    ...FORM_DATE_PICKER_COLOR_TOKEN_NAMES,
    ...FORM_DND_FILE_UPLOADER_COLOR_TOKEN_NAMES,
    ...FORM_INPUT_COLOR_TOKEN_NAMES,
    ...FORM_MENU_COLOR_TOKEN_NAMES,
    ...FORM_PILL_COLOR_TOKEN_NAMES,
    ...FORM_TOGGLE_SWITCH_COLOR_TOKEN_NAMES,
};

export const FORM_CHECKBOX_STYLE_TOKEN_NAMES = {
    FORM_CHECKBOX_BORDER_RADIUS: 'FORM_CHECKBOX_BORDER_RADIUS',
};

export const FORM_INPUT_STYLE_TOKEN_NAMES = {
    FORM_INPUT_BORDER_RADIUS: 'FORM_INPUT_BORDER_RADIUS',
    FORM_INPUT_BORDER_WIDTH: 'FORM_INPUT_BORDER_WIDTH',
    FORM_INPUT_PLACEHOLDER_FONT_STYLE: 'FORM_INPUT_PLACEHOLDER_FONT_STYLE',
};

export const FORM_MENU_STYLE_TOKEN_NAMES = {
    FORM_MENU_BORDER_RADIUS: 'FORM_MENU_BORDER_RADIUS',
};

export const FORM_PILL_STYLE_TOKEN_NAMES = {
    FORM_PILL_BORDER_RADIUS: 'FORM_PILL_BORDER_RADIUS',
};

export const FORM_TOGGLE_SWITCH_STYLE_TOKEN_NAMES = {
    FORM_TOGGLE_SWITCH_KNOB_BORDER_RADIUS:
        'FORM_TOGGLE_SWITCH_KNOB_BORDER_RADIUS',
    FORM_TOGGLE_SWITCH_TRACK_BORDER_RADIUS:
        'FORM_TOGGLE_SWITCH_TRACK_BORDER_RADIUS',
};

export const FORM_STYLE_TOKEN_NAMES = {
    ...FORM_CHECKBOX_STYLE_TOKEN_NAMES,
    ...FORM_INPUT_STYLE_TOKEN_NAMES,
    ...FORM_MENU_STYLE_TOKEN_NAMES,
    ...FORM_PILL_STYLE_TOKEN_NAMES,
    ...FORM_TOGGLE_SWITCH_STYLE_TOKEN_NAMES,
};

export const FORM_TOKEN_NAMES = {
    ...FORM_COLOR_TOKEN_NAMES,
    ...FORM_STYLE_TOKEN_NAMES,
};
