export const LINK_COLOR_TOKEN_NAMES = {
    LINK_TEXT_COLOR: 'LINK_TEXT_COLOR',
    LINK_FOCUS_HALO_COLOR: 'LINK_FOCUS_HALO_COLOR',
};

export const LINK_STYLE_TOKEN_NAMES = {
    LINK_BORDER_RADIUS: 'LINK_BORDER_RADIUS',
    LINK_TEXT_DECORATION: 'LINK_TEXT_DECORATION',
};

export const LINK_TOKEN_NAMES = {
    ...LINK_COLOR_TOKEN_NAMES,
    ...LINK_STYLE_TOKEN_NAMES,
};
