/* eslint-disable import/prefer-default-export */
const LOADING_COLOR_TOKEN_NAMES = {
    LOADING_ICON_ACCENT_COLOR: 'LOADING_ICON_ACCENT_COLOR',
    LOADING_ICON_PRIMARY_COLOR: 'LOADING_ICON_PRIMARY_COLOR',
    LOADING_ICON_SECONDARY_COLOR: 'LOADING_ICON_SECONDARY_COLOR',
    LOADING_SKELETON_BG_COLOR: 'LOADING_SKELETON_BG_COLOR',
    LOADING_SKELETON_ANIMATION_COLOR: 'LOADING_SKELETON_ANIMATION_COLOR',
};

export const LOADING_TOKEN_NAMES = {
    ...LOADING_COLOR_TOKEN_NAMES,
};
