export const MODAL_COLOR_TOKEN_NAMES = {
    MODAL_OVERLAY_BG_COLOR: 'MODAL_OVERLAY_BG_COLOR',
};

export const MODAL_STYLE_TOKEN_NAMES = {
    MODAL_DIALOG_BORDER_RADIUS: 'MODAL_DIALOG_BORDER_RADIUS',
};

export const MODAL_TOKEN_NAMES = {
    ...MODAL_COLOR_TOKEN_NAMES,
    ...MODAL_STYLE_TOKEN_NAMES,
};
