export const SECTION_STYLE_TOKEN_NAMES = {
    SECTION_BORDER_RADIUS: 'SECTION_BORDER_RADIUS',
    SECTION_HEADING_BORDER_WIDTH: 'SECTION_HEADING_BORDER_WIDTH',
};

export const SECTION_TOKEN_NAMES = {
    ...SECTION_STYLE_TOKEN_NAMES,
};
