export const TOASTER_COLOR_TOKEN_NAMES = {
    TOASTER_AFFIRMATIVE_BG_COLOR: 'TOASTER_AFFIRMATIVE_BG_COLOR',
    TOASTER_AFFIRMATIVE_TEXT_COLOR: 'TOASTER_AFFIRMATIVE_TEXT_COLOR',
    TOASTER_AFFIRMATIVE_PROGRESS_BAR_COLOR:
        'TOASTER_AFFIRMATIVE_PROGRESS_BAR_COLOR',
    TOASTER_BG_COLOR: 'TOASTER_BG_COLOR',
    TOASTER_CAUTIONARY_BG_COLOR: 'TOASTER_CAUTIONARY_BG_COLOR',
    TOASTER_CAUTIONARY_TEXT_COLOR: 'TOASTER_CAUTIONARY_TEXT_COLOR',
    TOASTER_CAUTIONARY_PROGRESS_BAR_COLOR:
        'TOASTER_CAUTIONARY_PROGRESS_BAR_COLOR',
    TOASTER_ERROR_BG_COLOR: 'TOASTER_ERROR_BG_COLOR',
    TOASTER_ERROR_TEXT_COLOR: 'TOASTER_ERROR_TEXT_COLOR',
    TOASTER_ERROR_PROGRESS_BAR_COLOR: 'TOASTER_ERROR_PROGRESS_BAR_COLOR',
    TOASTER_INFO_BG_COLOR: 'TOASTER_INFO_BG_COLOR',
    TOASTER_INFO_TEXT_COLOR: 'TOASTER_INFO_TEXT_COLOR',
    TOASTER_INFO_PROGRESS_BAR_COLOR: 'TOASTER_INFO_PROGRESS_BAR_COLOR',
    TOASTER_PROGRESS_BAR_COLOR: 'TOASTER_PROGRESS_BAR_COLOR',
    TOASTER_TEXT_COLOR: 'TOASTER_TEXT_COLOR',
};

export const TOASTER_STYLE_TOKEN_NAMES = {
    TOASTER_BORDER_RADIUS: 'TOASTER_BORDER_RADIUS',
};

export const TOASTER_TOKEN_NAMES = {
    ...TOASTER_COLOR_TOKEN_NAMES,
    ...TOASTER_STYLE_TOKEN_NAMES,
};
